Repository nugu-developers/nugu-linux, pull requests merged in 2019-12, with the labels that each got.

#69 fix nugu_sample
  examples/standalone/nugu_sample.cc
  examples/standalone/nugu_sample_manager.cc
  examples/standalone/nugu_sample_manager.hh
Labels: code quality, invalid

#68 optimize CapabilityType management
  include/interface/capability/capability_interface.hh
  interface/nugu_client_impl.cc
  service/capability/capability.cc
  service/capability_creator.cc
  service/capability_creator.hh
Labels: code quality

#70 System exception for common error
  examples/standalone/capability/system_listener.cc
  examples/standalone/capability/system_listener.hh
  examples/standalone/nugu_sample.cc
  include/interface/capability/capability_observer.hh
  include/interface/capability/system_interface.hh
  service/capability/system_agent.cc
Labels: enhancement, spec update

#71 Support mediaplayer
  include/core/nugu_player.h
  include/interface/media_player_interface.hh
  include/interface/nugu_client.hh
  interface/nugu_client.cc
  interface/nugu_client_impl.cc
  interface/nugu_client_impl.hh
  service/media_player.cc
  service/media_player.hh
Labels: enhancement

#72 optimize capability interface
  examples/standalone/capability/speech_operator.cc
  examples/standalone/capability/speech_operator.hh
  examples/standalone/nugu_sample.cc
  include/interface/capability/asr_interface.hh
  include/interface/capability/capability_interface.hh
  include/interface/capability/delegation_interface.hh
  include/interface/capability/display_interface.hh
  include/interface/capability/extension_interface.hh
  include/interface/capability/system_interface.hh
  include/interface/capability/text_interface.hh
  include/interface/capability/tts_interface.hh
  interface/capability_interface.cc
  interface/nugu_client_impl.cc
  interface/nugu_client_impl.hh
  service/capability/capability.hh
Labels: code quality

#73 network: fix attachment bug in is_end=1 case
  src/network/dg_server.c
Labels: bug

#74 build: fix cross compile issue
  CMakeLists.txt
  externals/CMakeLists.txt
  plugins/CMakeLists.txt
Labels: bug, ci/cd

#75 add log for initializing step
  interface/nugu_client_impl.cc
  plugins/gstreamer.c
Labels: code quality

#76 update Location Interface
  examples/standalone/capability/location_listener.cc
  examples/standalone/capability/location_listener.hh
  examples/standalone/capability/permission_manager.cc
  examples/standalone/nugu_sample.cc
  include/interface/capability/capability_interface.hh
  include/interface/capability/location_interface.hh
  include/interface/capability/permission_interface.hh
  service/capability/capability.cc
  service/capability/location_agent.cc
  service/capability/permission_agent.cc
  service/capability/permission_agent.hh
  service/capability_creator.cc
Labels: spec update

#78 log: change raw log message handling
  include/core/nugu_log.h
  plugins/portaudio.c
  src/network/http2/http2_request.c
  src/network/http2/v1_directives.cc
  src/nugu_log.c
Labels: bug, code quality

#77 fix bug.
  service/media_player.cc
Labels: bug, code quality

#79 update handling display render
  include/interface/capability/audio_player_interface.hh
  service/capability/audio_player_agent.cc
  service/capability/audio_player_agent.hh
  service/capability/display_agent.cc
  service/capability/display_agent.hh
  service/display_render_assembly.hh
  service/display_render_assembly.hpp
Labels: refactoring

#80 move token api to network manager
  examples/standalone/nugu_sample.cc
  include/core/nugu_network_manager.h
  include/interface/network_manager_interface.hh
  include/interface/nugu_configuration.hh
  interface/nugu_configuration.cc
  service/network_manager.cc
  service/network_manager.hh
  src/network/dg_registry.c
  src/network/dg_server.c
  src/nugu_network_manager.c
  src/nugu_uuid.c
Labels: code quality, refactoring

#81 update DisplayRenderAssembly efficiency
  service/capability/audio_player_agent.cc
  service/capability/display_agent.cc
  service/display_render_assembly.hh
  service/display_render_assembly.hpp
  service/playsync_manager.cc
  service/playsync_manager.hh
Labels: enhancement

#82 config: move UserAgent and RegistryDns to network
  CMakeLists.txt
  include/core/nugu_config.h
  include/core/nugu_network_manager.h
  include/interface/network_manager_interface.hh
  include/interface/nugu_configuration.hh
  interface/nugu_client_impl.cc
  interface/nugu_client_impl.hh
  interface/nugu_configuration.cc
  service/network_manager.cc
  service/network_manager.hh
  src/network/dg_registry.c
  src/network/dg_server.c
  src/network/http2/http2_network.c
  src/network/http2/v1_policies.cc
  src/nugu_network_manager.c
Labels: refactoring

#83 add nugu.h to manage build information
  .gitignore
  CMakeLists.txt
  examples/standalone/nugu_sample_manager.cc
  interface/CMakeLists.txt
  interface/nugu_client_impl.cc
  nugu.h.in
  src/nugu_network_manager.c
Labels: enhancement

#84 Add AudioRecorderManager
  interface/nugu_client_impl.cc
  service/audio_input_processor.cc
  service/audio_input_processor.hh
  service/audio_recorder_interface.hh
  service/audio_recorder_manager.cc
  service/audio_recorder_manager.hh
  service/speech_recognizer.cc
  service/wakeup_detector.cc
Labels: enhancement

#86 Refactoring config.
  include/core/nugu_config.h
  include/interface/nugu_client.hh
  include/interface/nugu_configuration.hh
  interface/nugu_client.cc
  interface/nugu_client_impl.cc
  interface/nugu_client_impl.hh
  interface/nugu_configuration.cc
  service/capability/asr_agent.cc
  service/capability/system_agent.cc
  service/capability/text_agent.cc
  service/capability/tts_agent.cc
  service/capability_manager.cc
  service/nugu_configuration.cc
  service/speech_recognizer.cc
  service/wakeup_detector.cc
  src/nugu_config.c
Labels: code quality, refactoring

#89 doc: change doxygen module tree
  doc/mainpage.dox
Labels: documentation

#88 network: split the handoff event
  core/capability/system_agent.cc
  include/base/nugu_network_manager.h
  src/nugu_network_manager.c
Labels: bug, enhancement

#90 fix typo error
  README.md
  clientkit/nugu_client_impl.cc
  core/capability/audio_player_agent.cc
  core/capability/audio_player_agent.hh
  core/capability/capability.cc
  core/capability/capability.hh
  core/capability/delegation_agent.cc
  core/capability/system_agent.cc
  include/base/nugu_focus.h
  include/base/nugu_media.h
  include/base/nugu_ringbuffer.h
  include/base/nugu_timer.h
  include/interface/media_player_interface.hh
  src/nugu_focus.c
  src/nugu_timer.c
Labels: code quality

#92 upgrade using vector efficiency
  core/audio_recorder_manager.cc
  core/capability/asr_agent.cc
  core/capability/audio_player_agent.cc
  core/capability/capability.cc
  core/capability_creator.hh
  core/capability_manager_helper.hh
  core/media_player.cc
  core/network_manager.cc
  core/playsync_manager.cc
Labels: code quality

#94 focus: remove MIC focus
  core/capability/asr_agent.cc
  core/capability/asr_agent.hh
  core/capability/audio_player_agent.cc
  core/capability/audio_player_agent.hh
  core/capability/system_agent.cc
  core/capability/tts_agent.cc
  core/capability/tts_agent.hh
  core/capability_manager.cc
  core/capability_manager.hh
  core/wakeup_handler.cc
  core/wakeup_handler.hh
  examples/standalone/capability/speech_operator.cc
  include/base/nugu_focus.h
  include/interface/wakeup_interface.hh
  src/nugu_focus.c
Labels: enhancement

#97 fix code style
  core/capability/asr_agent.cc
  core/capability/capability.hh
  core/wakeup_handler.hh
  examples/standalone/capability/display_listener.hh
  examples/standalone/capability/speech_operator.hh
  examples/standalone/capability/text_listener.hh
Labels: code quality

#98 network: fix long polling re-establish logic
  include/base/nugu_equeue.h
  src/network/http2/http2_network.c
  src/network/http2/v1_directives.cc
  src/network/http2/v1_directives.h
  src/nugu_network_manager.c
Labels: code quality

#99 upgrade efficiency
  core/capability/audio_player_agent.cc
  core/capability/display_agent.cc
  core/playsync_manager.cc
  core/playsync_manager.hh
Labels: code quality
