Repository nugu-developers/nugu-linux, pull requests merged in 2019-10, with the labels that each got.

#8 capability: update audioplayer
  service/capability/audio_player_agent.cc
Labels: spec update

#6 Refactoring SpeechRecognizer and WakeupDetector
  service/audio_input_processor.cc
  service/audio_input_processor.hh
  service/speech_recognizer.cc
  service/speech_recognizer.hh
  service/wakeup_detector.cc
  service/wakeup_detector.hh
Labels: refactoring

#7 remove dbus related code
  CMakeLists.txt
  Doxyfile
  include/core/nugu_dbus.h
  src/nugu_dbus.c
  src/nugu_pcm.c
  src/nugu_player.c
  src/nugu_plugin.c
Labels: code quality

#9 rename the contributing.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#10 adjust namespace of NuguConfig
  include/interface/capability/capability_observer.hh
  include/interface/media_player_interface.hh
  include/interface/network_manager_interface.hh
  include/interface/nugu_configuration.hh
  include/interface/wakeup_interface.hh
  interface/nugu_configuration.cc
  service/capability/asr_agent.cc
  service/capability_manager.cc
  service/speech_recognizer.cc
  service/wakeup_detector.cc
Labels: refactoring

#11 build: fix travis configuration
  .travis.yml
Labels: ci/cd

#12 Update README.md
  README.md
Labels: documentation

#14 fix static analysis issues
  service/capability/asr_agent.cc
  service/capability/audio_player_agent.cc
  service/capability/system_agent.cc
  service/capability/tts_agent.cc
  service/capability_manager.cc
  service/media_player.cc
  service/wakeup_handler.cc
Labels: code quality

#15 fix static analysis issues about CodeStyle
  examples/oob_setup/README.md
  service/capability_manager.cc
Labels: code quality

#17 fix static analysis issues
  include/core/nugu_log.h
  include/core/nugu_uuid.h
  service/speech_recognizer.cc
  service/wakeup_detector.cc
  src/http2/http2_network.c
  src/http2/v1_ping.c
  src/nugu_directive.c
  src/nugu_directive_sequencer.c
  src/nugu_log.c
  src/nugu_network_manager.c
  src/nugu_uuid.c
Labels: code quality

#18 apply custom duration in PlaySyncManager
  service/capability/display_agent.cc
  service/playsync_manager.cc
  service/playsync_manager.hh
Labels: enhancement

#19 Asr
  service/capability/asr_agent.cc
  service/capability/asr_agent.hh
Labels: bug, spec update

#20 config: add configs
  include/interface/nugu_configuration.hh
  interface/nugu_configuration.cc
  service/capability/asr_agent.cc
  service/capability/asr_agent.hh
  service/capability/text_agent.cc
  service/capability/text_agent.hh
  service/speech_recognizer.cc
Labels: enhancement

#22 config: bug fix.
  include/interface/nugu_configuration.hh
  interface/nugu_configuration.cc
  service/capability/asr_agent.cc
  service/capability/text_agent.cc
  service/speech_recognizer.cc
Labels: bug

#21 capability manager: check directive version
  include/interface/capability/capability_interface.hh
  service/capability/capability.hh
  service/capability_manager.cc
  service/capability_manager.hh
Labels: enhancement

#24 capability: update TTS interface
  include/interface/nugu_configuration.hh
  interface/nugu_configuration.cc
  service/capability/tts_agent.cc
Labels: spec update

#23 adjust log about context stack
  service/playsync_manager.cc
  service/playsync_manager.hh
Labels: code quality

#27 capability: update Extension interface
  include/interface/capability/extension_interface.hh
  service/capability/extension_agent.cc
  service/capability/extension_agent.hh
Labels: spec update

#26 capability: update Text interface
  service/capability/asr_agent.cc
  service/capability/text_agent.cc
  service/capability/text_agent.hh
Labels: spec update

#28 add delegation interface
  examples/standalone/delegation_listener.cc
  examples/standalone/delegation_listener.hh
  examples/standalone/nugu_sample.cc
  include/interface/capability/capability_interface.hh
  include/interface/capability/delegation_interface.hh
  include/interface/nugu_client.hh
  interface/nugu_client.cc
  service/capability/capability.cc
  service/capability/delegation_agent.cc
  service/capability/delegation_agent.hh
  service/capability_creator.cc
Labels: enhancement, spec update

#30 capability: update AudioPlayer interface
  include/interface/media_player_interface.hh
  service/capability/audio_player_agent.cc
  service/capability/audio_player_agent.hh
  service/media_player.cc
Labels: bug, enhancement, spec update

#29 capability: update System interface
  examples/standalone/system_listener.cc
  examples/standalone/system_listener.hh
  include/interface/capability/system_interface.hh
  interface/nugu_client_impl.cc
  service/capability/capability.cc
  service/capability/system_agent.cc
  service/capability/system_agent.hh
Labels: spec update

#31 implements common method in Capability
  service/capability/asr_agent.cc
  service/capability/asr_agent.hh
  service/capability/audio_player_agent.cc
  service/capability/audio_player_agent.hh
  service/capability/capability.cc
  service/capability/capability.hh
  service/capability/delegation_agent.cc
  service/capability/delegation_agent.hh
  service/capability/display_agent.cc
  service/capability/display_agent.hh
  service/capability/extension_agent.cc
  service/capability/extension_agent.hh
  service/capability/system_agent.cc
  service/capability/system_agent.hh
  service/capability/text_agent.cc
  service/capability/text_agent.hh
  service/capability/tts_agent.cc
  service/capability/tts_agent.hh
Labels: code quality
