Repository nugu-developers/nugu-linux, pull requests merged in 2019-11, with the labels that each got.

#32 capability: modify extension listener
  examples/standalone/extension_listener.cc
  examples/standalone/extension_listener.hh
  include/interface/capability/extension_interface.hh
  service/capability/extension_agent.cc
  service/capability/extension_agent.hh
Labels: refactoring

#33 refactoring the configuration
  examples/standalone/nugu_sample.cc
  include/interface/nugu_client.hh
  include/interface/nugu_configuration.hh
  interface/nugu_client.cc
  interface/nugu_client_impl.cc
  interface/nugu_client_impl.hh
  interface/nugu_configuration.cc
  service/speech_recognizer.cc
Labels: refactoring

#34 delegation:change context handling
  examples/standalone/delegation_listener.cc
  examples/standalone/delegation_listener.hh
  include/interface/capability/delegation_interface.hh
  service/capability/delegation_agent.cc
  service/capability/delegation_agent.hh
Labels: spec update

#35 asrgent: fix the bug.
  service/capability/asr_agent.cc
Labels: bug

#36 config: fix the bug.
  include/interface/nugu_configuration.hh
  interface/nugu_configuration.cc
Labels: bug

#37 refactoring the send event
  service/capability/asr_agent.cc
  service/capability/asr_agent.hh
  service/capability/audio_player_agent.cc
  service/capability/capability.cc
  service/capability/capability.hh
  service/capability/delegation_agent.cc
  service/capability/display_agent.cc
  service/capability/extension_agent.cc
  service/capability/system_agent.cc
  service/capability/text_agent.cc
  service/capability/tts_agent.cc
Labels: refactoring

#39 fix the bug.
  service/capability/asr_agent.cc
Labels: bug

#40 capability: fix text input event
  service/capability/text_agent.cc
Labels: bug

#43 remove hard-coding.
  include/interface/nugu_configuration.hh
  interface/nugu_configuration.cc
  service/audio_input_processor.cc
  service/audio_input_processor.hh
  service/speech_recognizer.cc
  service/wakeup_detector.cc
Labels: refactoring

#44 update handling display context
  examples/standalone/audio_player_listener.cc
  examples/standalone/audio_player_listener.hh
  examples/standalone/display_listener.cc
  examples/standalone/display_listener.hh
  include/interface/capability/audio_player_interface.hh
  include/interface/capability/delegation_interface.hh
  include/interface/capability/display_interface.hh
  service/capability/audio_player_agent.cc
  service/capability/audio_player_agent.hh
  service/capability/display_agent.cc
  service/capability/display_agent.hh
  service/playsync_manager.cc
  service/playsync_manager.hh
Labels: enhancement

#45 template: unified the template type
  service/capability/audio_player_agent.cc
  service/capability/display_agent.cc
Labels: enhancement

#46 Update creating CapabilityAgent Instance Policy
  interface/nugu_client_impl.cc
  service/capability_creator.cc
  service/capability_creator.hh
Labels: enhancement

#47 add referrer_dialog_request_id
  include/core/nugu_directive.h
  include/core/nugu_event.h
  src/http2/http2_manage.c
  src/http2/http2_manage.h
  src/nugu_event.c
  src/nugu_network_manager.c
Labels: enhancement, spec update

#48 Add metadata for multi display handling
  examples/standalone/audio_player_listener.cc
  examples/standalone/audio_player_listener.hh
  examples/standalone/display_listener.cc
  examples/standalone/display_listener.hh
  examples/standalone/extension_listener.cc
  examples/standalone/nugu_sample.cc
  examples/standalone/tts_listener.cc
  examples/standalone/tts_listener.hh
  include/interface/capability/audio_player_interface.hh
  include/interface/capability/display_interface.hh
  include/interface/capability/tts_interface.hh
  service/capability/audio_player_agent.cc
  service/capability/audio_player_agent.hh
  service/capability/display_agent.cc
  service/capability/display_agent.hh
  service/capability/tts_agent.cc
  service/capability/tts_agent.hh
  service/playsync_manager.cc
  service/playsync_manager.hh
Labels: enhancement, refactoring

#49 add permission interface
  examples/standalone/nugu_sample.cc
  examples/standalone/permission_listener.cc
  examples/standalone/permission_listener.hh
  include/interface/capability/capability_interface.hh
  include/interface/capability/permission_interface.hh
  service/capability/capability.cc
  service/capability/permission_agent.cc
  service/capability/permission_agent.hh
  service/capability_creator.cc
Labels: enhancement

#50 Code optimization nugu_sample and delegation_agent
  examples/standalone/nugu_sample.cc
  service/capability/delegation_agent.hh
Labels: code quality

#51 add LocationAgent
  examples/standalone/nugu_sample.cc
  examples/standalone/permission_manager.cc
  examples/standalone/permission_manager.hh
  include/interface/capability/capability_interface.hh
  include/interface/capability/location_interface.hh
  include/interface/capability/permission_interface.hh
  service/capability/capability.cc
  service/capability/capability.hh
  service/capability/location_agent.cc
  service/capability/location_agent.hh
  service/capability_creator.cc
Labels: enhancement

#52 apply playStackControl spec
  service/capability/audio_player_agent.cc
  service/capability/capability.cc
  service/capability/capability.hh
  service/capability/display_agent.cc
  service/capability/tts_agent.cc
  service/capability/tts_agent.hh
Labels: enhancement

#53 display:add stopRenderingTimer
  include/interface/capability/display_interface.hh
  service/capability/audio_player_agent.cc
  service/capability/audio_player_agent.hh
  service/capability/display_agent.cc
  service/capability/display_agent.hh
  service/playsync_manager.cc
  service/playsync_manager.hh
Labels: enhancement

#54 nugu_sample:divide UI code from nugu_sample
  examples/standalone/nugu_sample.cc
  examples/standalone/nugu_sample_manager.cc
  examples/standalone/nugu_sample_manager.hh
Labels: code quality

#56 capability: reduce common action
  service/capability/asr_agent.cc
  service/capability/asr_agent.hh
  service/capability/audio_player_agent.cc
  service/capability/audio_player_agent.hh
  service/capability/capability.cc
  service/capability/capability.hh
  service/capability/delegation_agent.cc
  service/capability/delegation_agent.hh
  service/capability/display_agent.cc
  service/capability/display_agent.hh
  service/capability/extension_agent.cc
  service/capability/extension_agent.hh
  service/capability/permission_agent.cc
  service/capability/permission_agent.hh
  service/capability/system_agent.cc
  service/capability/system_agent.hh
  service/capability/text_agent.cc
  service/capability/text_agent.hh
  service/capability/tts_agent.cc
  service/capability/tts_agent.hh
Labels: refactoring

#57 nugu_sample:optimize nugu_sample listener
  examples/standalone/CMakeLists.txt
  examples/standalone/capability/audio_player_listener.cc
  examples/standalone/capability/audio_player_listener.hh
  examples/standalone/capability/delegation_listener.cc
  examples/standalone/capability/delegation_listener.hh
  examples/standalone/capability/display_listener.cc
  examples/standalone/capability/display_listener.hh
  examples/standalone/capability/extension_listener.cc
  examples/standalone/capability/extension_listener.hh
  examples/standalone/capability/permission_manager.cc
  examples/standalone/capability/permission_manager.hh
  examples/standalone/capability/speech_operator.cc
  examples/standalone/capability/speech_operator.hh
  examples/standalone/capability/system_listener.cc
  examples/standalone/capability/system_listener.hh
  examples/standalone/capability/text_listener.cc
  examples/standalone/capability/text_listener.hh
  examples/standalone/capability/tts_listener.cc
  examples/standalone/capability/tts_listener.hh
  examples/standalone/nugu_sample_manager.cc
  include/interface/capability/audio_player_interface.hh
Labels: code quality

#59 Add user action
  service/capability/capability.cc
Labels: enhancement

#61 network: move src/http2 to src/network/http2
  src/CMakeLists.txt
  src/network/http2/gateway_registry.cc
  src/network/http2/gateway_registry.h
  src/network/http2/http2_manage.c
  src/network/http2/http2_manage.h
  src/network/http2/http2_network.c
  src/network/http2/http2_network.h
  src/network/http2/http2_request.c
  src/network/http2/http2_request.h
  src/network/http2/multipart_parser.c
  src/network/http2/multipart_parser.h
  src/network/http2/v1_directives.cc
  src/network/http2/v1_directives.h
  src/network/http2/v1_event.c
  src/network/http2/v1_event.h
  src/network/http2/v1_event_attachment.c
  src/network/http2/v1_event_attachment.h
  src/network/http2/v1_ping.c
  src/network/http2/v1_ping.h
Labels: refactoring

#63 update Doxyfile version
  Doxyfile
Labels: documentation

#65 network: fix status callback
  examples/standalone/nugu_sample.cc
  include/core/nugu_network_manager.h
  include/interface/network_manager_interface.hh
  interface/network_manager_interface.cc
  interface/nugu_client_impl.cc
  interface/nugu_client_impl.hh
  service/network_manager.cc
  src/nugu_network_manager.c
Labels: refactoring

#67 network: add handoff feature
  include/core/nugu_network_manager.h
  service/capability/system_agent.cc
  service/network_manager.cc
  src/nugu_network_manager.c
Labels: enhancement
