Repository nugu-developers/nugu-linux, pull requests merged in 2020-08, with the labels that each got.

#420 AudioPlayerAgent: fix the focus bug
  src/capability/audio_player_agent.cc
Labels: bug

#421 fix static analysis report
  src/capability/session_agent.cc
  src/core/session_manager.cc
  src/core/session_manager.hh
Labels: code quality

#422 Focus: Add hold/unhold functions
  include/clientkit/focus_manager_interface.hh
  src/capability/asr_agent.cc
  src/core/focus_manager.cc
  src/core/focus_manager.hh
  tests/core/test_core_focus_manager.cc
Labels: enhancement

#423 PlayStack:fix playstack removal condition
  src/capability/tts_agent.cc
Labels: bug

#424 Session:unhold focus when session deactivated
  src/capability/session_agent.cc
Labels: bug

#427 nugu_sample:remove unnecessary log
  examples/standalone/capability/audio_player_listener.cc
  examples/standalone/capability/speech_operator.cc
  examples/standalone/capability/system_listener.cc
  examples/standalone/capability/text_listener.cc
  examples/standalone/capability/text_listener.hh
  examples/standalone/nugu_sample.cc
  examples/standalone/nugu_sample_manager.cc
Labels: code quality

#425 log: fix ansi code for normal mode
  include/base/nugu_log.h
Labels: bug

#426 core: add cancel callback to DirectiveSequencer
  include/clientkit/capability.hh
  include/clientkit/capability_interface.hh
  include/clientkit/directive_sequencer_interface.hh
  src/clientkit/capability.cc
  src/core/capability_manager.cc
  src/core/capability_manager.hh
  src/core/directive_sequencer.cc
  src/core/directive_sequencer.hh
  tests/core/test_core_directive_sequencer.cc
Labels: enhancement

#428 SpeakerAgent: Fix the bug
  src/capability/speaker_agent.cc
Labels: bug

#429 build: add missing install files to package
  packaging/bionic/libnugu-examples.install
  packaging/xenial/libnugu-examples.install
Labels: bug

#430 TextInterface:add option for dialog attribute on requestTextInput
  examples/standalone/nugu_sample_manager.cc
  include/capability/text_interface.hh
  src/capability/text_agent.cc
  src/capability/text_agent.hh
Labels: enhancement

#431 interactionControl:add InteractionControlManager
  include/clientkit/capability.hh
  include/clientkit/capability_helper_interface.hh
  include/clientkit/interaction_control_manager_interface.hh
  src/clientkit/capability.cc
  src/core/capability_helper.cc
  src/core/capability_helper.hh
  src/core/capability_manager.cc
  src/core/capability_manager.hh
  src/core/interaction_control_manager.cc
  src/core/interaction_control_manager.hh
  tests/core/CMakeLists.txt
  tests/core/test_core_interaction_control_manager.cc
Labels: enhancement

#433 session:add to remove SessionManagerListener finally
  src/core/session_manager.cc
Labels: code quality

#434 interactionControl:apply multi-turn interaction mode
  examples/standalone/nugu_sample.cc
  include/clientkit/capability.hh
  src/capability/asr_agent.cc
  src/clientkit/capability.cc
Labels: enhancement

#435 ASR:fix to clear ExpectSpeech attributes
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/clientkit/capability.cc
Labels: bug

#432 Pcm: Add pcm player plugin using gstreamer
  CMakeLists.txt
  plugins/CMakeLists.txt
  plugins/gstreamer_pcm.c
Labels: enhancement

#436 SpeakerAgent: Set unable control
  examples/standalone/capability_collection.cc
  examples/standalone/capability_collection.hh
  include/capability/speaker_interface.hh
  src/capability/speaker_agent.cc
Labels: enhancement

#438 capability: add playServiceId to Text.TextSource
  src/capability/text_agent.cc
  src/capability/text_agent.hh
Labels: spec update

#440 ASRAgent: Fix the context information
  src/capability/asr_agent.cc
Labels: bug
