Repository nugu-developers/nugu-linux, pull requests merged in 2020-05, with the labels that each got.

#326 Gstreamer: fix the seek bug
  plugins/gstreamer.c
Labels: bug

#323 ASRAgent: Add cancel
  include/clientkit/capability_helper_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/capability/text_agent.cc
  src/capability/text_agent.hh
  src/core/audio_input_processor.cc
  src/core/capability_helper.cc
  src/core/capability_helper.hh
  src/core/capability_manager.cc
  src/core/capability_manager.hh
  src/core/speech_recognizer.cc
Labels: enhancement

#327 Capability: fix the suspend/restore issue
  include/clientkit/capability.hh
  plugins/gstreamer.c
  src/capability/audio_player_agent.cc
  src/capability/tts_agent.cc
Labels: bug

#330 Gstreamer: fix the bug.
  plugins/gstreamer.c
Labels: bug

#331 Refactoring network callback handling
  include/clientkit/capability_helper_interface.hh
  src/clientkit/nugu_client_impl.cc
  src/clientkit/nugu_client_impl.hh
  src/core/capability_helper.cc
  src/core/capability_helper.hh
  src/core/capability_manager.cc
  src/core/capability_manager.hh
  src/core/nugu_core_container.cc
  src/core/nugu_core_container.hh
Labels: refactoring

#332 TTSAgent: Update version 1.1
  src/capability/tts_agent.cc
Labels: spec update

#333 Capability:add method for receiving event response
  include/clientkit/capability.hh
  include/clientkit/capability_interface.hh
  src/clientkit/capability.cc
  src/core/capability_manager.cc
  src/core/capability_manager.hh
Labels: enhancement

#334 Capability:hide parseEventResultDesc to private
  include/clientkit/capability.hh
  src/clientkit/capability.cc
Labels: code quality

#336 AudioPlayer: Fix the bug.
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
Labels: bug

#337 examples: add revoke feature to oob_server
  examples/oob_setup/nugu_oob_server.py
Labels: enhancement

#338 network: fix NUL check bug in the response data
  src/base/network/http2/v1_policies.cc
Labels: bug

#339 base: add application log module
  include/base/nugu_log.h
  src/base/nugu_log.c
Labels: enhancement

#342 TTSAgent: Update version 1.2
  src/capability/tts_agent.cc
Labels: spec update

#344 AudioPlayerAgent: Update version 1.3
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
Labels: spec update

#343 core: add os info to client part
  src/core/capability_manager.cc
Labels: spec update

#345 capability: update System interface v1.2
  include/capability/system_interface.hh
  src/capability/system_agent.cc
Labels: spec update
