Repository nugu-developers/nugu-linux, pull requests merged in 2020-07, with the labels that each got.

#382 examples: add simple TTS application
  examples/CMakeLists.txt
  examples/simple_tts/CMakeLists.txt
  examples/simple_tts/main_tts.cc
Labels: enhancement

#381 capability: fix return type for property, command
  include/clientkit/capability.hh
  include/clientkit/capability_helper_interface.hh
  include/clientkit/capability_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
  src/capability/speaker_agent.cc
  src/capability/speaker_agent.hh
  src/capability/system_agent.cc
  src/capability/system_agent.hh
  src/capability/tts_agent.cc
  src/clientkit/capability.cc
  src/core/capability_helper.cc
  src/core/capability_helper.hh
  src/core/capability_manager.cc
  src/core/capability_manager.hh
Labels: code quality

#380 ASR:Adjust handling ExpectSpeech
  include/clientkit/capability.hh
  include/clientkit/capability_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/clientkit/capability.cc
  src/core/capability_manager.cc
  src/core/capability_manager.hh
  src/core/directive_sequencer.cc
Labels: enhancement

#383 plugins: add recording from file feature
  CMakeLists.txt
  plugins/portaudio.c
Labels: enhancement

#384 Session:Update SessionManager
  include/clientkit/session_manager_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/core/session_manager.cc
  src/core/session_manager.hh
  tests/core/test-core-session-manager.cc
Labels: enhancement

#386 PlayStack:Apply PlayStackManager in Capability Agents
  include/clientkit/capability.hh
  include/clientkit/capability_helper_interface.hh
  include/clientkit/playsync_manager_interface.hh
  src/capability/asr_agent.cc
  src/capability/audio_player_agent.cc
  src/capability/text_agent.cc
  src/capability/tts_agent.cc
  src/clientkit/capability.cc
  src/core/capability_helper.cc
  src/core/capability_helper.hh
  src/core/capability_manager.cc
  src/core/capability_manager.hh
  src/core/playstack_manager.cc
  src/core/playstack_manager.hh
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
  tests/core/test-core-playstack-manager.cc
Labels: enhancement

#387 PlayStack:optimize PlayStackManager Debug
  src/core/playstack_manager.cc
Labels: code quality, refactoring

#385 examples: add profiling measurement tool
  examples/CMakeLists.txt
  examples/profiling/CMakeLists.txt
  examples/profiling/README.md
  examples/profiling/main_prof.cc
  examples/profiling/testcases/4plus4.raw
  examples/profiling/testcases/date.raw
  examples/profiling/testcases/flo.raw
  examples/profiling/testcases/time.raw
  examples/profiling/testcases/weather.raw
  include/base/nugu_prof.h
  plugins/portaudio.c
  src/base/nugu_prof.c
Labels: enhancement

#389 build: fix ASAN default build option
  CMakeLists.txt
Labels: bug

#390 tests:apply fixture in PlayStackManager,SessionManager test
  tests/core/test-core-playstack-manager.cc
  tests/core/test-core-session-manager.cc
Labels: code quality

#388 AudioPlayerAgent: Modify control function
  include/capability/audio_player_interface.hh
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
Labels: spec update

#392 AudioPlayerAgent: Fix the bug.
  src/capability/audio_player_agent.cc
Labels: bug

#391 SessionManager:Upgrade to handle Multi-Agent Participation
  src/core/session_manager.cc
  src/core/session_manager.hh
  tests/core/test-core-session-manager.cc
Labels: enhancement

#394 ASRAgent:change the location of handling listening state
  src/capability/asr_agent.cc
Labels: enhancement

#395 ASRAgent:bug fix about cancel
  src/capability/asr_agent.cc
Labels: bug

#398 capability: add missing override annotation
  include/clientkit/capability.hh
Labels: code quality

#396 capability: add ResetConnection to SystemAgent
  include/base/nugu_network_manager.h
  src/base/nugu_network_manager.c
  src/capability/system_agent.cc
  src/capability/system_agent.hh
Labels: enhancement

#399 core: add missing map erase to directive sequencer
  src/core/directive_sequencer.cc
Labels: bug

#397 dialog:fix to handle previous dialog
  include/clientkit/capability.hh
  include/clientkit/playstack_manager_interface.hh
  src/capability/audio_player_agent.cc
  src/capability/tts_agent.cc
  src/clientkit/capability.cc
  src/core/playstack_manager.cc
  src/core/playstack_manager.hh
  tests/core/test-core-playstack-manager.cc
Labels: bug, enhancement

#402 plugin: fix plugin de-initialize order
  src/base/nugu_pcm.c
  src/base/nugu_player.c
  src/base/nugu_plugin.c
  src/base/nugu_recorder.c
Labels: code quality

#403 RDRID: fix the bug
  src/capability/tts_agent.cc
Labels: bug

#401 plugins: separate the portaudio into sub-modules
  CMakeLists.txt
  plugins/CMakeLists.txt
  plugins/portaudio.c
  plugins/portaudio_pcm_async.c
  plugins/portaudio_pcm_sync.c
  plugins/portaudio_recorder.c
  src/base/nugu_pcm.c
Labels: code quality, refactoring

#406 network: fix event send callback
  examples/standalone/nugu_sample.cc
  include/base/nugu_network_manager.h
  include/clientkit/network_manager_interface.hh
  src/base/nugu_network_manager.c
  src/clientkit/network_manager_interface.cc
  src/core/network_manager.cc
Labels: enhancement

#409 AudioPlayerAgent: Update version 1.4
  src/capability/audio_player_agent.cc
Labels: spec update

#410 session:apply session clearance
  include/clientkit/session_manager_interface.hh
  src/clientkit/capability.cc
  src/core/session_manager.cc
  src/core/session_manager.hh
  tests/core/test_core_session_manager.cc
Labels: bug

#411 Remove static analysis(clang-tidy) report
  examples/profiling/main_prof.cc
  plugins/portaudio_pcm_async.c
  plugins/portaudio_pcm_sync.c
  src/core/directive_sequencer.cc
  src/core/playstack_manager.cc
Labels: code quality

#412 capability: fix double free issue
  src/clientkit/capability.cc
Labels: bug

#415 TextAgent:apply const reference on requestTextInput
  include/capability/text_interface.hh
  src/capability/text_agent.cc
  src/capability/text_agent.hh
Labels: code quality

#414 capability:add condition about processing previous directive
  include/clientkit/playstack_manager_interface.hh
  src/clientkit/capability.cc
  src/core/playstack_manager.cc
  src/core/playstack_manager.hh
  tests/core/test_core_playstack_manager.cc
Labels: enhancement

#413 profiling: enhance the csv reporting result
  examples/profiling/main_prof.cc
  src/base/nugu_prof.c
Labels: enhancement

#417 ASRAgent:remove unnecessary method
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
Labels: code quality

#418 Session:add SessionManagerListener
  include/clientkit/session_manager_interface.hh
  src/core/session_manager.cc
  src/core/session_manager.hh
  tests/core/test_core_session_manager.cc
Labels: enhancement

#419 Session:notify session state
  examples/standalone/capability/session_listener.cc
  examples/standalone/capability/session_listener.hh
  examples/standalone/capability_collection.cc
  examples/standalone/capability_collection.hh
  include/capability/session_interface.hh
  src/capability/session_agent.cc
  src/capability/session_agent.hh
  src/core/session_manager.cc
  tests/core/test_core_session_manager.cc
Labels: enhancement
