Repository nugu-developers/nugu-linux, pull requests merged in 2020-10, with the labels that each got.

#466 Capability&Core:improve SDK life cycle handling
  examples/standalone/nugu_sample_manager.cc
  examples/standalone/nugu_sdk_manager.cc
  examples/standalone/nugu_sdk_manager.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
  src/capability/display_agent.cc
  src/capability/display_agent.hh
  src/capability/mic_agent.cc
  src/capability/mic_agent.hh
  src/capability/session_agent.cc
  src/capability/sound_agent.cc
  src/capability/speaker_agent.cc
  src/capability/speaker_agent.hh
  src/capability/system_agent.cc
  src/capability/system_agent.hh
  src/capability/text_agent.cc
  src/capability/text_agent.hh
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
  src/clientkit/capability.cc
  src/clientkit/nugu_client_impl.cc
  src/core/capability_manager.cc
  src/core/capability_manager.hh
  src/core/directive_sequencer.cc
  src/core/directive_sequencer.hh
  src/core/focus_manager.cc
  src/core/focus_manager.hh
  src/core/interaction_control_manager.cc
  src/core/interaction_control_manager.hh
  src/core/nugu_core_container.cc
  src/core/nugu_core_container.hh
  src/core/playstack_manager.cc
  src/core/playstack_manager.hh
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
  src/core/session_manager.cc
  src/core/session_manager.hh
Labels: enhancement

#467 plugins: remove a pending timer when pcm_destroy
  plugins/portaudio_pcm_async.c
Labels: bug

#468 Session:add reset test for SessionManager
  tests/core/test_core_session_manager.cc
Labels: code quality

#469 interaction:add reset test for InteractionControlManager
  src/core/interaction_control_manager.cc
  src/core/interaction_control_manager.hh
  tests/core/test_core_interaction_control_manager.cc
Labels: code quality

#470 playsync:add reset test for PlaySyncManager
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
  tests/core/test_core_playsync_manager.cc
Labels: code quality

#471 playstack:add reset test for PlayStackManager
  src/core/playstack_manager.cc
  src/core/playstack_manager.hh
  tests/core/test_core_playstack_manager.cc
Labels: code quality

#472 playstack:fix to stop timer when resetting PlayStackManager
  src/core/playstack_manager.cc
  tests/core/test_core_playstack_manager.cc
Labels: bug

#473 NuguClient:add getCapabilityHandler
  include/clientkit/nugu_client.hh
  src/clientkit/nugu_client.cc
Labels: enhancement

#475 nugu_sample:add to show playstack info
  examples/standalone/nugu_sample_manager.cc
  examples/standalone/nugu_sample_manager.hh
  examples/standalone/nugu_sdk_manager.cc
  examples/standalone/nugu_sdk_manager.hh
Labels: enhancement

#477 Timer: Add loop property
  include/base/nugu_timer.h
  include/clientkit/nugu_timer_interface.hh
  src/base/nugu_timer.c
  src/core/nugu_timer.cc
  src/core/nugu_timer.hh
  tests/core/test_core_nugu_timer.cc
  tests/core/test_core_nugu_timer_mock.cc
  tests/test_nugu_timer.c
Labels: enhancement

#478 examples: fix memory leak in the asr/text filter
  examples/response_filter/filter.cc
  examples/response_filter/main.cc
Labels: bug

#479 Player: Modified using timer
  src/core/media_player.cc
  src/core/tts_player.cc
Labels: refactoring

#480 playsync:update playsync and playstack management for handling Alerts
  include/clientkit/playsync_manager_interface.hh
  src/core/playstack_manager.cc
  src/core/playstack_manager.hh
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
  tests/core/test_core_playsync_manager.cc
Labels: enhancement

#481 playstack:remove playstack interface
  include/clientkit/playstack_manager_interface.hh
  include/clientkit/playsync_manager_interface.hh
  src/core/playstack_manager.hh
Labels: code quality

#482 SpeakerAgent:compose SpeakerType and name string maps
  src/capability/speaker_agent.cc
  src/capability/speaker_agent.hh
Labels: code quality

#483 AudioPlayer: Clear context information
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
Labels: enhancement

#484 TTS:fix handling sync state result
  include/clientkit/capability.hh
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
  src/clientkit/capability.cc
Labels: bug

#485 Timer: Refactoring nugu timer
  include/base/nugu_timer.h
  include/clientkit/nugu_core_container_interface.hh
  include/clientkit/nugu_timer_interface.hh
  src/base/nugu_timer.c
  src/capability/asr_agent.cc
  src/capability/system_agent.cc
  src/capability/text_agent.cc
  src/core/media_player.cc
  src/core/nugu_core_container.cc
  src/core/nugu_core_container.hh
  src/core/nugu_timer.cc
  src/core/nugu_timer.hh
  src/core/playstack_manager.cc
  src/core/speech_recognizer.cc
  src/core/tts_player.cc
  src/core/wakeup_detector.cc
  tests/core/test_core_nugu_timer.cc
  tests/core/test_core_nugu_timer_mock.cc
  tests/test_nugu_timer.c
Labels: refactoring

#486 playsync:fix playsync postpone release
  src/core/playsync_manager.cc
Labels: bug

#487 SpeakerAgent: Update interface v1.2
  include/capability/speaker_interface.hh
  src/capability/speaker_agent.cc
Labels: spec update

#488 TTSAgent: Update interface v1.3
  src/capability/tts_agent.cc
Labels: spec update

#489 FocusManager: Added focus request priority
  include/clientkit/focus_manager_interface.hh
  src/core/focus_manager.cc
  src/core/focus_manager.hh
  tests/core/test_core_focus_manager.cc
Labels: enhancement

#490 base: fix typo
  src/base/network/http2/v1_directives.c
Labels: bug
