Repository nugu-developers/nugu-linux, pull requests merged in 2020-03, with the labels that each got.

#205 remove add-on capability
  examples/standalone/capability/delegation_listener.cc
  examples/standalone/capability/delegation_listener.hh
  examples/standalone/capability/extension_listener.cc
  examples/standalone/capability/extension_listener.hh
  examples/standalone/capability/location_listener.cc
  examples/standalone/capability/location_listener.hh
  examples/standalone/capability_collection.hh
  include/capability/capability_factory.hh
  include/capability/delegation_interface.hh
  include/capability/extension_interface.hh
  include/capability/location_interface.hh
  src/capability/capability_factory.cc
  src/capability/delegation_agent.cc
  src/capability/delegation_agent.hh
  src/capability/extension_agent.cc
  src/capability/extension_agent.hh
  src/capability/location_agent.cc
  src/capability/location_agent.hh
Labels: code quality

#206 network: add notify callback for event send
  include/base/nugu_network_manager.h
  src/base/nugu_network_manager.c
Labels: enhancement

#209 NetworkManager: Event Send/Result Listener
  examples/standalone/nugu_sample.cc
  include/clientkit/capability_helper_interface.hh
  include/clientkit/network_manager_interface.hh
  src/clientkit/network_manager_interface.cc
  src/clientkit/nugu_client_impl.cc
  src/clientkit/nugu_client_impl.hh
  src/core/capability_helper.cc
  src/core/capability_helper.hh
  src/core/capability_manager.cc
  src/core/capability_manager.hh
  src/core/network_manager.cc
Labels: enhancement, refactoring

#210 network: fix request resume bug
  src/base/network/http2/directives_parser.cc
  src/base/network/http2/http2_network.c
  src/base/network/http2/http2_network.h
  src/base/network/http2/http2_request.c
  src/base/network/http2/http2_request.h
  src/base/network/http2/v1_directives.c
  src/base/network/http2/v1_events.c
Labels: bug

#207 Asr 1.1
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
Labels: spec update

#211 network: introduce /v2/events
  CMakeLists.txt
  src/base/CMakeLists.txt
  src/base/network/dg_server.c
  src/base/network/http2/v2_events.c
  src/base/network/http2/v2_events.h
Labels: enhancement

#213 add method about EpdSilenceInterval
  include/capability/asr_interface.hh
  include/clientkit/speech_recognizer_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/core/speech_recognizer.cc
  src/core/speech_recognizer.hh
Labels: enhancement

#215 build: add option for vendor library
  CMakeLists.txt
  src/capability/asr_agent.cc
  src/core/speech_recognizer.cc
  src/core/wakeup_detector.cc
  tests/CMakeLists.txt
Labels: code quality

#216 network: add missing EXPORT_API
  src/base/nugu_network_manager.c
Labels: bug

#217 clientkit: ignore the plugin loading result
  src/clientkit/nugu_client_impl.cc
Labels: bug

#219 network: add /v2/ping
  src/base/network/dg_server.c
  src/base/network/http2/v1_ping.c
  src/base/network/http2/v1_ping.h
Labels: enhancement

#220 externals: add tizen ca path patch to curl
  externals/0004_tizen_ca_bundle_path.patch
  externals/patch_curl.sh
Labels: enhancement

#222 build: add log message ansicolor option
  CMakeLists.txt
  include/base/nugu_log.h
  src/base/nugu_log.c
Labels: enhancement

#223 Pcm: Add get_position and get_duration
  include/base/nugu_pcm.h
  plugins/portaudio.c
  src/base/nugu_pcm.c
Labels: enhancement

#225 Portaudio double free heap
  plugins/portaudio.c
Labels: bug, enhancement

#226 Pcm: fix the heap-use-after-free
  src/base/nugu_pcm.c
Labels: bug

#227 Refactoring TTSAgent
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
Labels: refactoring

#214 Audioplayer attachment
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
Labels: enhancement

#228 externals: fix opus library build options
  CMakeLists.txt
  externals/CMakeLists.txt
Labels: bug

#229 build: fix asan link order
  CMakeLists.txt
Labels: bug

#231 Timer: Update time unit
  include/clientkit/nugu_timer_interface.hh
  src/capability/asr_agent.cc
  src/capability/system_agent.cc
  src/capability/text_agent.cc
  src/core/nugu_timer.cc
  src/core/playsync_manager.cc
  tests/core-timer/nugu_timer_mock.cc
  tests/core-timer/test-core-NuguTimer.cc
Labels: enhancement

#234 TextAgent: Request & Response mapping #233
  examples/standalone/capability/text_listener.cc
  examples/standalone/capability/text_listener.hh
  examples/standalone/nugu_sample_manager.cc
  include/capability/text_interface.hh
  include/clientkit/capability.hh
  src/capability/asr_agent.cc
  src/capability/text_agent.cc
  src/capability/text_agent.hh
  src/clientkit/capability.cc
Labels: enhancement

#235 TTSAgent: Request & Response mapping #233
  examples/standalone/capability/tts_listener.cc
  include/capability/tts_interface.hh
  include/clientkit/capability.hh
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
  src/clientkit/capability.cc
Labels: enhancement

#236 ASRAgent: Request & Response mapping #233
  examples/simple_asr/main_asr.cc
  examples/standalone/capability/speech_operator.cc
  examples/standalone/capability/speech_operator.hh
  include/capability/asr_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
Labels: enhancement

#237 Focus: modify focus priority
  include/base/nugu_focus.h
  src/base/nugu_focus.c
  src/capability/asr_agent.cc
  src/capability/tts_agent.cc
Labels: enhancement

#238 base: add missing push_data call to push_data_done
  plugins/filedump.c
  src/base/nugu_pcm.c
Labels: bug

#240 AudioPlayerAgent: Request & Response mapping nugu-developers#233
  examples/standalone/capability/audio_player_listener.cc
  examples/standalone/capability/audio_player_listener.hh
  include/capability/audio_player_interface.hh
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
Labels: enhancement

#241 SystemAgent: Request & Response mapping nugu-developers#233
  examples/standalone/capability/system_listener.cc
  examples/standalone/capability/system_listener.hh
  include/capability/system_interface.hh
  src/capability/system_agent.cc
Labels: enhancement

#242 capability: remove 'Disconnect' from SystemAgent
  include/capability/system_interface.hh
  src/capability/system_agent.cc
  src/capability/system_agent.hh
Labels: enhancement

#244 Capability: fix the hang-up issue.
  src/clientkit/capability.cc
Labels: bug

#243 network: remove 'address' filed from policy
  include/base/nugu_network_manager.h
  src/base/network/http2/v1_policies.cc
  src/capability/system_agent.cc
Labels: enhancement

#245 AudioPlayerAgent: Update version 1.2
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
Labels: spec update

#246 TextAgent: Update specification
  src/capability/asr_agent.cc
  src/capability/text_agent.cc
  src/capability/text_agent.hh
Labels: spec update

#248 AudioRecorderManager: Fix a bug
  src/core/audio_recorder_manager.cc
Labels: bug

#249 TextAgent: Update version 1.1
  src/capability/text_agent.cc
Labels: spec update

#247 ASRAgent: Fix status and event occurrence
  include/capability/asr_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/core/speech_recognizer.cc
  src/core/wakeup_detector.cc
  src/core/wakeup_handler.cc
Labels: bug, code quality

#257 ASRAgent: Apply RDRID #251
  include/clientkit/capability.hh
  src/capability/asr_agent.cc
Labels: enhancement

#255 TTSAgent: Apply RDRID #251
  include/capability/tts_interface.hh
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
Labels: enhancement

#254 TextAgent: Apply RDRID #251
  src/capability/text_agent.cc
Labels: enhancement

#253 MicAgent: Apply RDRID #251
  src/capability/mic_agent.cc
  src/capability/mic_agent.hh
Labels: enhancement

#256 SpeakerAgent: Apply RDRID #251
  src/capability/speaker_agent.cc
  src/capability/speaker_agent.hh
Labels: enhancement

#258 clientkit: add missing destructor for listener
  include/clientkit/media_player_interface.hh
Labels: bug

#259 ASR, KWD: Fix the multi-thread issue
  examples/standalone/capability/speech_operator.cc
  include/clientkit/speech_recognizer_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/core/audio_input_processor.cc
  src/core/audio_input_processor.hh
  src/core/speech_recognizer.cc
  src/core/speech_recognizer.hh
  src/core/wakeup_detector.cc
  src/core/wakeup_detector.hh
  src/core/wakeup_handler.cc
  src/core/wakeup_handler.hh
Labels: bug

#261 Thread: fix the hangup issue
  src/core/audio_input_processor.cc
Labels: enhancement
