Repository nugu-developers/nugu-linux, pull requests merged in 2020-04, with the labels that each got.

#263 AudioPlayerAgent: Update RDRID
  src/capability/audio_player_agent.cc
  src/clientkit/capability.cc
Labels: enhancement

#264 SystemAgent: Apply RDRID
  src/capability/system_agent.cc
Labels: enhancement

#265 ASRAgent: support multi-wakeup feature
  examples/standalone/capability/speech_operator.cc
  examples/standalone/capability/speech_operator.hh
  include/capability/asr_interface.hh
  include/clientkit/wakeup_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/core/wakeup_detector.cc
  src/core/wakeup_detector.hh
  src/core/wakeup_handler.cc
  src/core/wakeup_handler.hh
Labels: enhancement

#266 network: add message-id to /v2/events attachment
  src/base/network/dg_server.c
  src/base/network/http2/v2_events.c
  src/base/network/http2/v2_events.h
Labels: spec update

#267 base: add stdout to log system
  include/base/nugu_log.h
  src/base/nugu_log.c
Labels: enhancement

#268 AudioPlayer: fix the event payload
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
Labels: bug

#270 Audioplayer: Fix the playback position bug
  src/core/media_player.cc
  src/core/media_player.hh
Labels: bug

#271 fix asr expecting speech bug
  src/capability/asr_agent.cc
Labels: bug

#269 Capability: update event's context
  include/clientkit/capability_helper_interface.hh
  src/clientkit/capability.cc
  src/core/capability_helper.cc
  src/core/capability_helper.hh
  src/core/capability_manager.cc
  src/core/capability_manager.hh
Labels: enhancement

#275 network: fix multipart issue
  src/base/network/dg_server.c
  src/base/network/http2/http2_network.c
  src/base/network/http2/http2_network.h
  src/base/network/http2/multipart_parser.c
  src/base/network/http2/v2_events.c
  src/base/network/http2/v2_events.h
Labels: bug

#277 add SoundAgent
  examples/standalone/capability/sound_listener.cc
  examples/standalone/capability/sound_listener.hh
  examples/standalone/capability_collection.cc
  examples/standalone/capability_collection.hh
  examples/standalone/nugu_sample.cc
  include/capability/capability_factory.hh
  include/capability/sound_interface.hh
  src/capability/capability_factory.cc
  src/capability/sound_agent.cc
  src/capability/sound_agent.hh
Labels: enhancement

#276 network: add response code callback
  src/base/network/http2/http2_request.c
  src/base/network/http2/http2_request.h
  src/base/network/http2/v2_events.c
Labels: enhancement

#278 ASRAgent: Fix the bug
  src/capability/asr_agent.cc
Labels: bug

#279 Capability: Get wakeup keyword
  include/clientkit/capability_helper_interface.hh
  src/core/capability_helper.cc
  src/core/capability_helper.hh
  src/core/capability_manager.cc
  src/core/capability_manager.hh
Labels: enhancement

#281 update TextAgent for handling text by application
  examples/standalone/capability/text_listener.cc
  examples/standalone/capability/text_listener.hh
  include/capability/text_interface.hh
  src/capability/text_agent.cc
Labels: enhancement

#284 network: add libcurl error code to http2_request
  src/base/network/http2/http2_network.c
  src/base/network/http2/http2_request.c
  src/base/network/http2/http2_request.h
Labels: enhancement

#283 Gstreamer: Stabilization
  plugins/gstreamer.c
Labels: bug

#285 base: introduce profiling feature
  examples/standalone/nugu_sample.cc
  include/base/nugu_log.h
  include/base/nugu_prof.h
  include/base/nugu_uuid.h
  src/base/network/dg_server.c
  src/base/network/http2/http2_request.c
  src/base/network/http2/http2_request.h
  src/base/network/http2/v2_events.c
  src/base/nugu_log.c
  src/base/nugu_prof.c
  src/clientkit/nugu_client_impl.cc
Labels: enhancement

#288 Gstreamer: Fix the bug
  plugins/gstreamer.c
Labels: bug

#290 AudioPlayer: fix the bug
  src/capability/audio_player_agent.cc
Labels: bug

#293 Update to handle Call focus
  include/base/nugu_focus.h
  include/clientkit/playsync_manager_interface.hh
  src/base/nugu_focus.c
  src/capability/tts_agent.cc
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
Labels: enhancement

#295 Update to refresh PlaysyncLayer
  src/core/playsync_manager.cc
Labels: code quality, enhancement

#296 Apply changed context maintenance policy
  include/clientkit/playsync_manager_interface.hh
  src/capability/asr_agent.cc
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
Labels: code quality, enhancement

#299 Optimize nugu_sample code
  examples/standalone/nugu_sample.cc
Labels: code quality

#301 core: fix media player default volume setting
  src/core/media_player.cc
Labels: bug

#302 Optimize NuguSampleManager
  examples/standalone/nugu_sample.cc
  examples/standalone/nugu_sample_manager.cc
  examples/standalone/nugu_sample_manager.hh
Labels: code quality, refactoring

#305 Upgrade TTS Text Display
  examples/standalone/capability/tts_listener.cc
  examples/standalone/capability/tts_listener.hh
Labels: enhancement

#306 Remove NuguClientListener
  include/clientkit/nugu_client.hh
  include/clientkit/nugu_client_listener.hh
  src/clientkit/nugu_client.cc
  src/clientkit/nugu_client_impl.cc
  src/clientkit/nugu_client_impl.hh
Labels: code quality

#309 Update to set EPD attribute by ASRAgent
  include/capability/asr_interface.hh
  include/clientkit/nugu_core_container_interface.hh
  include/clientkit/speech_recognizer_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/core/nugu_core_container.cc
  src/core/nugu_core_container.hh
Labels: enhancement

#311 base: fix http2 curl log
  src/base/network/http2/http2_request.c
Labels: code quality

#312 Fix typo error
  examples/standalone/capability/system_listener.hh
  examples/standalone/capability_collection.hh
  examples/standalone/nugu_sample_manager.cc
  include/capability/audio_player_interface.hh
  include/capability/tts_interface.hh
  include/clientkit/capability.hh
  include/clientkit/capability_interface.hh
  include/clientkit/playsync_manager_interface.hh
  src/capability/audio_player_agent.cc
Labels: code quality

#313 Gstreamer: remove unnecessary code
  plugins/gstreamer.c
Labels: code quality

#314 Change use to smart pointer
  examples/standalone/capability_collection.cc
  include/capability/speaker_interface.hh
  src/capability/speaker_agent.cc
  src/capability/speaker_agent.hh
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
Labels: code quality

#315 Clang: fix the static analysis report
  examples/standalone/nugu_sample_manager.cc
  src/base/network/http2/http2_request.c
  src/base/nugu_log.c
  src/core/audio_input_processor.cc
  src/core/media_player.cc
Labels: code quality

#316 AudioPlayerAgent: Fix the sendEventPlaybackPaused
  src/capability/audio_player_agent.cc
Labels: bug
