Repository nugu-developers/nugu-linux, pull requests merged in 2020-11, with the labels that each got.

#491 playsync:add flag for check next display to render exists
  examples/standalone/capability/audio_player_listener.cc
  examples/standalone/capability/audio_player_listener.hh
  examples/standalone/capability/display_listener.cc
  examples/standalone/capability/display_listener.hh
  include/capability/display_interface.hh
  include/clientkit/playsync_manager_interface.hh
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
  src/capability/display_agent.cc
  src/capability/display_agent.hh
  src/core/playstack_manager.cc
  src/core/playstack_manager.hh
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
  tests/core/test_core_playstack_manager.cc
  tests/core/test_core_playsync_manager.cc
Labels: enhancement

#493 example:refactoring AudioPlayerListener
  examples/standalone/capability/audio_player_listener.cc
  examples/standalone/capability/audio_player_listener.hh
  examples/standalone/capability/display_listener.cc
  examples/standalone/capability/display_listener.hh
  include/capability/display_interface.hh
Labels: code quality

#494 playstack:renaming methods of PlayStackManager test
  tests/core/test_core_playstack_manager.cc
Labels: code quality

#495 test:fix static analysis issues
  tests/core/test_core_playstack_manager.cc
  tests/core/test_core_playsync_manager.cc
Labels: code quality

#497 playsync:fix timer handling in PlaySyncManager test
  tests/core/test_core_playsync_manager.cc
Labels: bug

#498 playstack:reset PlayStackManager Timer started flag
  src/core/nugu_timer.hh
  src/core/playstack_manager.cc
  src/core/playstack_manager.hh
Labels: bug

#496 ASRAgent: Fixed the server response error
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
Labels: bug

#492 FocusManager: Applied nugu sound policy
  examples/standalone/nugu_sdk_manager.cc
  examples/standalone/nugu_sdk_manager.hh
  include/clientkit/focus_manager_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/capability/audio_player_agent.cc
  src/capability/session_agent.cc
  src/capability/tts_agent.cc
  src/core/focus_manager.cc
  src/core/focus_manager.hh
  tests/core/test_core_focus_manager.cc
Labels: enhancement, spec update

#500 playstack:adjust checking next display info
  src/core/playstack_manager.cc
  src/core/playstack_manager.hh
  tests/core/test_core_playstack_manager.cc
Labels: enhancement

#501 ASRAgent: Modified the ASR focus
  src/capability/asr_agent.cc
Labels: enhancement

#503 capability: update Text interface to v1.4
  src/capability/text_agent.cc
  src/capability/text_agent.hh
Labels: spec update

#502 ASRAgent: Update interface v1.4
  include/clientkit/speech_recognizer_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/core/speech_recognizer.cc
  src/core/speech_recognizer.hh
Labels: spec update

#504 playstack:Add method for changing playstack hold time
  src/core/playstack_manager.cc
  src/core/playstack_manager.hh
  tests/core/test_core_playstack_manager.cc
  tests/core/test_core_playsync_manager.cc
Labels: enhancement

#506 TTS:fix handling TTS.Stop directive
  src/capability/tts_agent.cc
Labels: bug

#508 add Github action
  .github/workflows/main.yml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
Labels: ci/cd

#510 capabiliy:reinforce destroyDirective
  src/capability/audio_player_agent.cc
  src/capability/tts_agent.cc
  src/clientkit/capability.cc
Labels: enhancement

#509 ASRAgent:Add EPD Attribute setter/getter
  include/capability/asr_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
Labels: enhancement

#511 AudioPlayer:apply media pause playstack policy
  include/clientkit/playsync_manager_interface.hh
  src/capability/audio_player_agent.cc
  src/core/playstack_manager.cc
  src/core/playstack_manager.hh
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
  tests/core/test_core_playstack_manager.cc
  tests/core/test_core_playsync_manager.cc
Labels: enhancement

#512 add Github Action for tag
  .github/workflows/doxygen.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
Labels: ci/cd

#514 base: change strdup to g_strdup
  src/base/network/http2/directives_parser.cc
  src/base/network/http2/http2_request.c
  src/base/network/http2/v1_event.c
  src/base/network/http2/v1_event_attachment.c
  src/base/network/http2/v2_events.c
  src/base/nugu_directive.c
  src/base/nugu_event.c
  src/base/nugu_network_manager.c
  src/base/nugu_prof.c
  src/base/nugu_uuid.c
Labels: code quality

#513 core: add missing header includes
  src/core/directive_sequencer.cc
  src/core/tts_player.cc
  tests/core/test_core_directive_sequencer.cc
Labels: code quality

#516 TextAgent:apply Text Interface v1.5 spec
  include/capability/text_interface.hh
  src/capability/text_agent.cc
  src/capability/text_agent.hh
Labels: spec update

#518 capability:change has_attachment variable name
  include/clientkit/capability.hh
  src/capability/audio_player_agent.cc
  src/capability/tts_agent.cc
  src/clientkit/capability.cc
Labels: invalid

#517 build: add feature definition macro
  CMakeLists.txt
  examples/CMakeLists.txt
  plugins/CMakeLists.txt
  src/CMakeLists.txt
Labels: code quality

#519 build: add check for API symbol exist
  CMakeLists.txt
  src/base/network/http2/http2_network.c
  src/base/nugu_equeue.c
  src/base/nugu_log.c
  src/core/audio_input_processor.cc
Labels: code quality

#520 Utility:Add Utility Interface and Agent.
  examples/standalone/capability_collection.cc
  examples/standalone/capability_collection.hh
  include/capability/capability_factory.hh
  include/capability/utility_interface.hh
  src/capability/capability_factory.cc
  src/capability/utility_agent.cc
  src/capability/utility_agent.hh
Labels: spec update

#521 TextAgent:remove validation check for text and token
  src/capability/text_agent.cc
Labels: enhancement

#523 base: add policy to NuguDirective
  include/base/nugu_directive.h
  include/clientkit/directive_sequencer_interface.hh
  src/base/nugu_directive.c
  src/core/directive_sequencer.cc
  src/core/directive_sequencer.hh
  tests/test_nugu_directive.c
Labels: code quality, spec update

#522 core: add ANY medium to DirectiveSequencer
  src/capability/utility_agent.cc
  src/core/directive_sequencer.cc
  src/core/directive_sequencer.hh
  tests/core/test_core_directive_sequencer.cc
Labels: spec update

#524 DisplayRender:Add DisplayRenderHelper
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
  src/capability/display_agent.cc
  src/capability/display_agent.hh
  src/capability/display_render_helper.cc
  src/capability/display_render_helper.hh
Labels: code quality, refactoring
