Repository nugu-developers/nugu-linux, pull requests merged in 2020-01, with the labels that each got.

#101 network: add debug info to curl build
  externals/CMakeLists.txt
  src/CMakeLists.txt
  src/network/http2/http2_network.c
  src/nugu_network_manager.c
Labels: code quality

#100 examples: add token refresh to oob server
  examples/oob_setup/nugu_oob_server.py
Labels: enhancement

#102 remove warning
  clientkit/nugu_client.cc
  clientkit/nugu_client_impl.cc
  core/audio_input_processor.cc
  core/audio_input_processor.hh
  core/audio_recorder_manager.cc
  core/capability/asr_agent.cc
  core/capability/audio_player_agent.cc
  core/capability/audio_player_agent.hh
  core/capability/capability.cc
  core/capability/delegation_agent.cc
  core/capability/display_agent.cc
  core/capability/extension_agent.cc
  core/capability/extension_agent.hh
  core/capability/location_agent.cc
  core/capability/system_agent.cc
  core/capability/text_agent.cc
  core/capability/tts_agent.cc
  core/capability_creator.cc
  core/capability_creator.hh
  core/capability_manager.cc
  core/capability_manager.hh
  core/capability_manager_helper.cc
  core/capability_manager_helper.hh
  core/playsync_manager.cc
  core/playsync_manager.hh
  examples/standalone/capability/speech_operator.cc
  examples/standalone/capability/tts_listener.cc
  examples/standalone/nugu_sample.cc
  examples/standalone/nugu_sample_manager.cc
  examples/standalone/nugu_sample_manager.hh
  include/clientkit/nugu_client.hh
  src/network/http2/v1_directives.cc
  src/nugu_directive_sequencer.c
  src/nugu_plugin.c
Labels: code quality

#103 ringbuffer: fix the bug
  src/nugu_ringbuffer.c
  tests/test-nugu-ringbuffer.c
Labels: bug

#104 base: add EXPORT_API to equeue
  src/nugu_equeue.c
Labels: bug

#105 plugins: add init status check to gstreamer
  plugins/gstreamer.c
Labels: code quality

#106 update referrer_dialog_id
  core/capability/capability.cc
Labels: spec update

#108 fix the bug.
  core/capability/asr_agent.cc
Labels: bug

#109 Update System v1.1
  core/capability/system_agent.cc
  core/capability/system_agent.hh
  examples/standalone/capability/system_listener.cc
  examples/standalone/capability/system_listener.hh
  include/interface/capability/system_interface.hh
Labels: spec update

#107 Update Extension v1.1
  core/capability/extension_agent.cc
  core/capability/extension_agent.hh
  include/interface/capability/extension_interface.hh
Labels: spec update

#110 TTS: add cancel event
  core/capability/tts_agent.cc
  core/capability_manager.cc
  core/capability_manager.hh
  examples/standalone/capability/tts_listener.cc
  examples/standalone/capability/tts_listener.hh
  include/interface/capability/tts_interface.hh
Labels: enhancement

#111 Update AudioPlayer v1.1
  core/capability/audio_player_agent.cc
  core/capability/audio_player_agent.hh
  core/capability/capability.cc
  core/capability/capability.hh
  core/capability/tts_agent.cc
  examples/standalone/capability/audio_player_listener.cc
  examples/standalone/capability/audio_player_listener.hh
  examples/standalone/capability/display_listener.cc
  examples/standalone/capability/display_listener.hh
  include/interface/capability/audio_player_interface.hh
  include/interface/capability/display_interface.hh
Labels: spec update

#114 examples: add graceful shutdown to oob server
  examples/oob_setup/nugu_oob_server.py
Labels: code quality

#116 build: disable asan on debian packaging
  CMakeLists.txt
  packaging/bionic/rules
  packaging/xenial/rules
Labels: code quality

#115 remove CapabilityType
  clientkit/nugu_client.cc
  clientkit/nugu_client_impl.cc
  clientkit/nugu_client_impl.hh
  core/capability/asr_agent.cc
  core/capability/asr_agent.hh
  core/capability/audio_player_agent.cc
  core/capability/audio_player_agent.hh
  core/capability/capability.cc
  core/capability/capability.hh
  core/capability/delegation_agent.cc
  core/capability/display_agent.cc
  core/capability/extension_agent.cc
  core/capability/location_agent.cc
  core/capability/mic_agent.cc
  core/capability/system_agent.cc
  core/capability/system_agent.hh
  core/capability/text_agent.cc
  core/capability/text_agent.hh
  core/capability/tts_agent.cc
  core/capability_creator.cc
  core/capability_creator.hh
  core/capability_manager.cc
  core/capability_manager.hh
  core/display_render_assembly.hpp
  core/playsync_manager.cc
  core/playsync_manager.hh
  core/wakeup_handler.cc
  examples/standalone/nugu_sample.cc
  include/clientkit/nugu_client.hh
  include/interface/capability/capability_interface.hh
Labels: refactoring

#117 build: fix warnings on clang-tidy
  CMakeLists.txt
  src/CMakeLists.txt
Labels: code quality

#119 build: fix build warnings on clang
  include/interface/capability/audio_player_interface.hh
  src/core/capability/asr_agent.cc
  src/core/capability/asr_agent.hh
  src/core/capability/audio_player_agent.hh
  src/core/capability/capability.hh
  src/core/capability/display_agent.hh
  src/core/capability/tts_agent.hh
  src/core/display_render_assembly.hh
Labels: code quality

#121 remove each capability handler getter
  examples/standalone/nugu_sample.cc
  include/clientkit/nugu_client.hh
  include/interface/capability/capability_observer.hh
  src/clientkit/nugu_client.cc
  src/core/capability/capability.cc
Labels: refactoring

#123 Remove NuguInterface namespace
  examples/standalone/capability/speech_operator.hh
  examples/standalone/nugu_sample.cc
  include/capability/capability_factory.hh
  include/clientkit/media_player_interface.hh
  include/clientkit/network_manager_interface.hh
  include/clientkit/nugu_client.hh
  include/clientkit/nugu_configuration.hh
  include/clientkit/wakeup_interface.hh
  src/CMakeLists.txt
  src/capability/asr_agent.cc
  src/capability/audio_player_agent.hh
  src/capability/capability_factory.cc
  src/capability/text_agent.cc
  src/capability/tts_agent.cc
  src/clientkit/network_manager_interface.cc
  src/clientkit/nugu_client_impl.cc
  src/clientkit/nugu_client_impl.hh
  src/clientkit/nugu_configuration.cc
  src/core/capability_manager.cc
  src/core/media_player.hh
  src/core/network_manager.hh
  src/core/nugu_core_container.cc
  src/core/nugu_core_container.hh
  src/core/speech_recognizer.cc
  src/core/wakeup_detector.cc
  src/core/wakeup_handler.hh
  src/interface/CMakeLists.txt
Labels: refactoring
