Repository nugu-developers/nugu-linux, pull requests merged in 2020-12, with the labels that each got.

#525 core: fix DirectiveSequencer idle callback bug
  src/core/directive_sequencer.cc
  tests/core/test_core_directive_sequencer.cc
Labels: bug

#526 utility:construct UtilityAgent in NuguClient
  examples/standalone/nugu_sdk_manager.cc
Labels: spec update

#527 core: fix memory leak in DirectiveSequencer
  src/core/directive_sequencer.cc
Labels: bug

#528 capability: add missing initialize to UtilityAgent
  src/capability/utility_agent.cc
Labels: bug

#529 add Github Action about clang-tidy
  .github/workflows/pull_request.yaml
  CMakeLists.txt
  src/core/directive_sequencer.cc
Labels: ci/cd

#530 AudioPlayer:apply AudioPlayer Interface 1.5
  src/capability/audio_player_agent.cc
Labels: spec update

#532 Curl: ca_bundle_path patch
  externals/0004_curl_ca_bundle_path.patch
  externals/patch_curl.sh
Labels: enhancement

#533 session:compose recent sessionId in same playServiceId
  src/core/session_manager.cc
  tests/core/test_core_session_manager.cc
Labels: spec update

#534 session:apply session flow in DisplayAgent
  examples/standalone/capability/display_listener.cc
  examples/standalone/capability/display_listener.hh
  examples/standalone/capability_collection.cc
  src/capability/display_agent.cc
  src/core/session_manager.cc
  tests/core/test_core_session_manager.cc
Labels: enhancement

#535 session:apply multi-session maintenance flow
  src/capability/display_agent.cc
  src/capability/display_agent.hh
  tests/core/test_core_session_manager.cc
Labels: enhancement

#536 extension:add Extension Interface v1.1
  examples/standalone/capability/extension_listener.cc
  examples/standalone/capability/extension_listener.hh
  examples/standalone/capability_collection.cc
  examples/standalone/capability_collection.hh
  examples/standalone/nugu_sdk_manager.cc
  include/capability/capability_factory.hh
  include/capability/extension_interface.hh
  src/capability/capability_factory.cc
  src/capability/extension_agent.cc
  src/capability/extension_agent.hh
Labels: spec update

#537 chips:add Chips Interface v1.1
  examples/standalone/capability/chips_listener.cc
  examples/standalone/capability/chips_listener.hh
  examples/standalone/capability_collection.cc
  examples/standalone/capability_collection.hh
  examples/standalone/nugu_sdk_manager.cc
  include/capability/capability_factory.hh
  include/capability/chips_interface.hh
  src/capability/capability_factory.cc
  src/capability/chips_agent.cc
  src/capability/chips_agent.hh
Labels: spec update

#538 Display:apply directive blocking policy
  src/capability/display_agent.cc
  src/capability/display_agent.hh
Labels: enhancement

#539 Chips:apply directive blocking policy
  src/capability/chips_agent.cc
  src/capability/chips_agent.hh
Labels: enhancement

#540 Chips:extends ChipContent Model to ChipsInfo
  examples/standalone/capability/chips_listener.cc
  examples/standalone/capability/chips_listener.hh
  include/capability/chips_interface.hh
  src/capability/chips_agent.cc
Labels: enhancement

#541 DirectiveSequencer:change to notify cancelDirective about pending list
  src/core/directive_sequencer.cc
Labels: enhancement

#542 TTS:handle TTS.Stop directive correctly
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
Labels: enhancement
