Repository nugu-developers/nugu-linux, pull requests merged in 2020-02, with the labels that each got.

#125 remove NuguConfig
  examples/standalone/nugu_sample.cc
  include/capability/asr_interface.hh
  include/capability/capability_factory.hh
  include/capability/text_interface.hh
  include/capability/tts_interface.hh
  include/clientkit/nugu_client.hh
  include/clientkit/nugu_configuration.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/capability/capability_factory.cc
  src/capability/text_agent.cc
  src/capability/text_agent.hh
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
  src/clientkit/nugu_client.cc
  src/clientkit/nugu_client_impl.cc
  src/clientkit/nugu_client_impl.hh
  src/clientkit/nugu_configuration.cc
  src/core/capability_manager.cc
  src/core/nugu_core_container.cc
  src/core/nugu_core_container.hh
  src/core/speech_recognizer.cc
  src/core/speech_recognizer.hh
  src/core/wakeup_detector.cc
  src/core/wakeup_detector.hh
  src/core/wakeup_handler.cc
  src/core/wakeup_handler.hh
Labels: code quality, refactoring

#126 Apply INuguCoreContainer to CapabilityAgent
  examples/standalone/nugu_sample.cc
  include/capability/capability_interface.hh
  include/clientkit/nugu_client.hh
  include/clientkit/nugu_core_container_interface.hh
  include/clientkit/speech_recognizer_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/capability/audio_player_agent.cc
  src/capability/capability.cc
  src/capability/capability.hh
  src/clientkit/nugu_client.cc
  src/clientkit/nugu_client_impl.cc
  src/clientkit/nugu_client_impl.hh
  src/core/nugu_core_container.cc
  src/core/nugu_core_container.hh
  src/core/speech_recognizer.hh
Labels: refactoring

#127 add method to change wakeup word
  include/clientkit/nugu_client.hh
  src/clientkit/nugu_client.cc
  src/clientkit/nugu_client_impl.cc
  src/clientkit/nugu_client_impl.hh
  src/core/capability_manager_helper.cc
  src/core/capability_manager_helper.hh
Labels: enhancement

#129 fix the hangup issue.
  src/core/playsync_manager.hh
Labels: bug

#130 add CapabilityHelper for handling NuguCore
  include/clientkit/capability_helper_interface.hh
  include/clientkit/nugu_core_container_interface.hh
  include/clientkit/playsync_manager_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
  src/capability/capability.cc
  src/capability/capability.hh
  src/capability/delegation_agent.cc
  src/capability/display_agent.cc
  src/capability/display_agent.hh
  src/capability/display_render_assembly.hh
  src/capability/display_render_assembly.hpp
  src/capability/extension_agent.cc
  src/capability/mic_agent.cc
  src/capability/system_agent.cc
  src/capability/text_agent.cc
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
  src/core/capability_helper.cc
  src/core/capability_helper.hh
  src/core/capability_manager.hh
  src/core/nugu_core_container.cc
  src/core/nugu_core_container.hh
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
Labels: refactoring

#131 network: fix missing close_data bug
  src/base/network/dg_server.c
  src/base/network/http2/v1_event_attachment.c
Labels: bug

#132 base: add type to nugu_event
  include/base/nugu_event.h
  src/base/nugu_event.c
  src/capability/asr_agent.cc
  src/capability/capability.cc
  src/capability/capability.hh
Labels: enhancement

#133 change capability_interface namespace
  include/capability/asr_interface.hh
  include/capability/audio_player_interface.hh
  include/capability/capability_factory.hh
  include/capability/delegation_interface.hh
  include/capability/display_interface.hh
  include/capability/extension_interface.hh
  include/capability/location_interface.hh
  include/capability/mic_interface.hh
  include/capability/speaker_interface.hh
  include/capability/system_interface.hh
  include/capability/text_interface.hh
  include/capability/tts_interface.hh
  include/clientkit/capability_interface.hh
  include/clientkit/capability_observer.hh
  include/clientkit/nugu_client.hh
  include/clientkit/nugu_client_listener.hh
  src/capability/audio_player_agent.hh
  src/capability/capability.hh
  src/clientkit/nugu_client_impl.cc
  src/clientkit/nugu_client_impl.hh
  src/core/capability_manager.hh
  src/core/capability_manager_helper.hh
  src/core/media_player.hh
  src/core/playsync_manager.hh
Labels: refactoring

#135 remove CapabilityManagerHelper
  src/clientkit/nugu_client_impl.cc
  src/core/capability_manager_helper.cc
  src/core/capability_manager_helper.hh
  src/core/nugu_core_container.cc
  src/core/nugu_core_container.hh
  src/core/playsync_manager.hh
Labels: code quality, refactoring

#134 network: add /v1/events API support
  CMakeLists.txt
  include/base/nugu_network_manager.h
  src/base/CMakeLists.txt
  src/base/network/dg_server.c
  src/base/network/dg_server.h
  src/base/network/http2/http2_request.c
  src/base/network/http2/v1_events.c
  src/base/network/http2/v1_events.h
  src/base/nugu_log.c
  src/base/nugu_network_manager.c
  src/capability/asr_agent.cc
  src/capability/capability.cc
  src/capability/capability.hh
Labels: enhancement

#137 change method to add capability
  examples/standalone/capability/speaker_listener.cc
  examples/standalone/capability/speaker_listener.hh
  examples/standalone/nugu_sample.cc
  include/capability/capability_factory.hh
  include/clientkit/nugu_client.hh
  src/capability/capability_factory.cc
  src/clientkit/nugu_client.cc
  src/clientkit/nugu_client_impl.cc
  src/clientkit/nugu_client_impl.hh
Labels: enhancement, refactoring

#138 network: fix to stop ping when ping fails
  src/base/network/dg_server.c
  src/base/network/dg_server.h
  src/base/nugu_network_manager.c
Labels: bug

#139 network: fix to use random boundary for /v1/events
  include/base/nugu_uuid.h
  src/base/network/http2/v1_events.c
  src/base/nugu_uuid.c
Labels: enhancement

#136 doc: update doxygen document
  doc/mainpage.dox
  include/clientkit/speech_recognizer_interface.hh
  src/core/audio_recorder_manager.cc
Labels: documentation

#141 update documentation
  include/capability/asr_interface.hh
  include/capability/audio_player_interface.hh
  include/capability/capability_factory.hh
  include/capability/display_interface.hh
  include/capability/location_interface.hh
  include/capability/speaker_interface.hh
  include/capability/system_interface.hh
  include/capability/text_interface.hh
  include/capability/tts_interface.hh
  include/clientkit/capability_helper_interface.hh
  include/clientkit/nugu_client_listener.hh
  include/clientkit/nugu_core_container_interface.hh
  include/clientkit/playsync_manager_interface.hh
Labels: documentation

#142 Documentation
  include/capability/asr_interface.hh
  include/capability/display_interface.hh
  include/capability/location_interface.hh
  include/capability/speaker_interface.hh
  include/capability/system_interface.hh
  include/capability/text_interface.hh
  include/capability/tts_interface.hh
  include/clientkit/capability_helper_interface.hh
  include/clientkit/capability_interface.hh
  include/clientkit/network_manager_interface.hh
  include/clientkit/playsync_manager_interface.hh
  include/clientkit/speech_recognizer_interface.hh
  include/clientkit/wakeup_interface.hh
Labels: documentation

#146 update setting capability listener
  examples/simple_asr/main_asr.cc
  examples/simple_text/main_text.cc
  examples/standalone/nugu_sample.cc
  include/capability/capability_factory.hh
  src/capability/capability_factory.cc
Labels: code quality

#148 Move role capability instance management
  examples/capability_injection/battery_agent.cc
  examples/capability_injection/battery_agent.hh
  examples/capability_injection/main_capability_injection.cc
  examples/simple_asr/main_asr.cc
  examples/simple_text/main_text.cc
  examples/standalone/nugu_sample.cc
  include/clientkit/capability_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
  src/capability/capability.cc
  src/capability/capability.hh
  src/capability/system_agent.cc
  src/capability/system_agent.hh
  src/capability/text_agent.cc
  src/capability/text_agent.hh
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
  src/clientkit/nugu_client_impl.cc
Labels: code quality, refactoring

#147 network: add event send result handler
  include/base/nugu_equeue.h
  include/base/nugu_network_manager.h
  src/base/network/dg_server.c
  src/base/network/dg_types.h
  src/base/network/http2/http2_request.c
  src/base/network/http2/http2_request.h
  src/base/network/http2/v1_event.c
  src/base/network/http2/v1_event.h
  src/base/network/http2/v1_events.c
  src/base/network/http2/v1_events.h
  src/base/nugu_network_manager.c
Labels: enhancement

#149 Remove capability handler getter
  examples/standalone/nugu_sample.cc
  include/clientkit/nugu_client.hh
  src/clientkit/nugu_client.cc
Labels: code quality

#150 base: export dlsym API to nugu_plugin
  include/base/nugu_plugin.h
  src/base/nugu_plugin.c
  tests/CMakeLists.txt
  tests/plugin_dummy.c
  tests/plugin_nugu.c
  tests/plugin_nugu_custom.c
  tests/test-nugu-plugin.c
Labels: enhancement

#152 remove ICapabilityObserver
  examples/capability_injection/battery_agent.cc
  examples/capability_injection/battery_agent.hh
  examples/standalone/nugu_sample.cc
  include/clientkit/capability_interface.hh
  include/clientkit/capability_observer.hh
  include/clientkit/nugu_client_listener.hh
  src/capability/capability.cc
  src/capability/capability.hh
  src/clientkit/nugu_client_impl.cc
Labels: code quality

#153 base: fix heap-use-after-free bug
  src/base/network/http2/v1_event.c
  src/base/network/http2/v1_events.c
Labels: bug

#154 AudioPlayerAgent: Sync event with Play service
  src/capability/audio_player_agent.cc
Labels: bug

#155 base: add protocol log support
  include/base/nugu_log.h
  src/base/network/http2/http2_request.c
  src/base/network/http2/http2_request.h
  src/base/network/http2/v1_directives.cc
  src/base/network/http2/v1_event_attachment.c
  src/base/network/http2/v1_policies.cc
  src/base/nugu_log.c
  src/base/nugu_network_manager.c
Labels: enhancement

#156 Capability: Remove deinitialize
  src/capability/asr_agent.cc
  src/capability/audio_player_agent.cc
  src/capability/system_agent.cc
  src/capability/text_agent.cc
  src/capability/tts_agent.cc
Labels: enhancement

#157 Speaker: modify parser
  src/capability/audio_player_agent.cc
  src/capability/speaker_agent.cc
Labels: spec update

#158 Open Base Capability publicly
  include/clientkit/capability.hh
  src/capability/asr_agent.hh
  src/capability/audio_player_agent.hh
  src/capability/capability.hh
  src/capability/delegation_agent.hh
  src/capability/display_agent.hh
  src/capability/extension_agent.hh
  src/capability/location_agent.hh
  src/capability/mic_agent.hh
  src/capability/speaker_agent.hh
  src/capability/system_agent.hh
  src/capability/text_agent.hh
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
  src/clientkit/capability.cc
Labels: code quality, refactoring

#159 add missing nugu_ prefix to public APIs
  include/base/nugu_audio.h
  include/base/nugu_buffer.h
  include/base/nugu_decoder.h
  include/base/nugu_directive.h
  include/base/nugu_directive_sequencer.h
  include/base/nugu_log.h
  include/base/nugu_media.h
  include/base/nugu_network_manager.h
  include/base/nugu_pcm.h
  include/base/nugu_player.h
  include/base/nugu_timer.h
  plugins/filedump.c
  plugins/gstreamer.c
  plugins/opus.c
  plugins/portaudio.c
  src/base/network/dg_registry.c
  src/base/network/dg_server.c
  src/base/network/http2/http2_network.c
  src/base/network/http2/http2_request.c
  src/base/network/http2/multipart_parser.c
  src/base/network/http2/v1_directives.cc
  src/base/network/http2/v1_event.c
  src/base/network/http2/v1_event_attachment.c
  src/base/network/http2/v1_events.c
  src/base/network/http2/v1_ping.c
  src/base/network/http2/v1_policies.cc
  src/base/nugu_buffer.c
  src/base/nugu_decoder.c
  src/base/nugu_directive.c
  src/base/nugu_directive_sequencer.c
  src/base/nugu_equeue.c
  src/base/nugu_event.c
  src/base/nugu_focus.c
  src/base/nugu_network_manager.c
  src/base/nugu_pcm.c
  src/base/nugu_player.c
  src/base/nugu_plugin.c
  src/base/nugu_recorder.c
  src/base/nugu_ringbuffer.c
  src/base/nugu_timer.c
  src/capability/tts_agent.cc
  src/core/audio_recorder_manager.cc
  src/core/capability_manager.cc
  src/core/capability_manager.hh
  src/core/media_player.cc
  tests/core-timer/nugu_timer_mock.cc
  tests/test-nugu-buffer.c
  tests/test-nugu-decoder.c
  tests/test-nugu-pcm.c
  tests/test-nugu-player.c
  tests/test-nugu-recorder.c
Labels: code quality

#160 MicAgent: modify parser
  src/capability/mic_agent.cc
Labels: spec update

#161 Directive: Add directive groups
  include/base/nugu_directive.h
  src/base/network/http2/v1_directives.cc
  src/base/nugu_directive.c
  tests/test-nugu-directive.c
Labels: enhancement

#163 tests: fix build error on allwinner target
  tests/core-timer/nugu_timer_mock.cc
  tests/core-timer/test-core-NuguTimer.cc
Labels: bug

#162 Focus
  include/base/nugu_focus.h
  include/clientkit/capability_helper_interface.hh
  src/base/nugu_focus.c
  src/capability/asr_agent.cc
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
  src/core/capability_manager.cc
Labels: enhancement

#164 Focus: release asr focus
  src/capability/asr_agent.cc
  src/capability/system_agent.cc
  src/capability/system_agent.hh
  src/core/capability_manager.cc
  src/core/capability_manager.hh
Labels: enhancement

#165 SpeakerAgent: modify API
  examples/standalone/capability/speaker_listener.cc
  include/capability/speaker_interface.hh
  src/capability/speaker_agent.cc
  src/capability/speaker_agent.hh
Labels: bug, enhancement

#166 EPD, KWD: recorder mute
  include/capability/asr_interface.hh
  include/clientkit/speech_recognizer_interface.hh
  include/clientkit/wakeup_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/core/audio_input_processor.cc
  src/core/audio_input_processor.hh
  src/core/speech_recognizer.cc
  src/core/speech_recognizer.hh
  src/core/wakeup_detector.cc
  src/core/wakeup_detector.hh
  src/core/wakeup_handler.cc
  src/core/wakeup_handler.hh
Labels: enhancement

#168 Focus: release asr focus
  src/core/capability_manager.cc
Labels: bug

#167 Open Capability Default Attribute Value
  include/capability/asr_interface.hh
  include/capability/text_interface.hh
  include/capability/tts_interface.hh
  src/capability/asr_agent.cc
  src/capability/text_agent.cc
  src/capability/tts_agent.cc
Labels: enhancement

#169 network: add thread synchronization module
  src/base/CMakeLists.txt
  src/base/network/http2/http2_network.c
  src/base/network/http2/threadsync.c
  src/base/network/http2/threadsync.h
Labels: code quality

#170 Adjust CapabilityBuilder accessibility
  include/clientkit/nugu_client.hh
  src/clientkit/nugu_client.cc
Labels: code quality

#172 add comment on capability attribute
  include/capability/asr_interface.hh
  include/capability/speaker_interface.hh
  include/capability/text_interface.hh
  include/capability/tts_interface.hh
Labels: documentation

#171 network: add synchronized event send
  include/base/nugu_network_manager.h
  include/clientkit/capability.hh
  src/base/network/dg_server.c
  src/base/network/dg_server.h
  src/base/network/dg_types.h
  src/base/network/http2/v1_event.c
  src/base/network/http2/v1_event.h
  src/base/network/http2/v1_events.c
  src/base/network/http2/v1_events.h
  src/base/nugu_network_manager.c
  src/capability/system_agent.cc
  src/clientkit/capability.cc
Labels: enhancement

#173 network: add synchronized event send to /v1/events
  src/base/network/http2/v1_events.c
Labels: enhancement

#177 base: fix directive sequencer callback concept
  include/base/nugu_directive_sequencer.h
  src/base/nugu_directive_sequencer.c
  src/core/capability_manager.cc
Labels: bug

#176 remove display interface
  examples/standalone/capability/audio_player_listener.cc
  examples/standalone/capability/audio_player_listener.hh
  examples/standalone/capability/display_listener.cc
  examples/standalone/capability/display_listener.hh
  examples/standalone/nugu_sample.cc
  include/capability/audio_player_interface.hh
  include/capability/capability_factory.hh
  include/capability/display_interface.hh
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
  src/capability/capability_factory.cc
  src/capability/display_agent.cc
  src/capability/display_agent.hh
  src/capability/display_render_assembly.hh
  src/capability/display_render_assembly.hpp
Labels: refactoring, spec update

#178 SystemAgent: Remove context info
  examples/standalone/capability/system_listener.cc
  examples/standalone/capability/system_listener.hh
  include/capability/system_interface.hh
  src/capability/system_agent.cc
Labels: spec update

#179 examples: change lvh.me to localhost
  examples/oob_setup/README.md
  examples/oob_setup/nugu_oob_server.py
Labels: enhancement

#180 Apply recent play context policy
  include/clientkit/playsync_manager_interface.hh
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
Labels: enhancement

#182 Recorder: modify the mutex
  src/base/nugu_recorder.c
  src/core/audio_input_processor.cc
  src/core/audio_recorder_manager.cc
Labels: bug

#183 SpeakerAgent: update api
  examples/standalone/capability/speaker_listener.cc
  examples/standalone/capability/speaker_listener.hh
  include/capability/speaker_interface.hh
  src/capability/speaker_agent.cc
  src/capability/speaker_agent.hh
Labels: bug, enhancement

#184 add capabilty suspend,restore
  examples/capability_injection/battery_agent.cc
  examples/capability_injection/battery_agent.hh
  include/clientkit/capability.hh
  include/clientkit/capability_helper_interface.hh
  include/clientkit/capability_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
  src/clientkit/capability.cc
  src/core/capability_helper.cc
  src/core/capability_helper.hh
  src/core/capability_manager.cc
  src/core/capability_manager.hh
Labels: enhancement

#185 build: add build options to plugins
  CMakeLists.txt
  plugins/CMakeLists.txt
Labels: enhancement

#186 examples: add graceful exit to sample program
  examples/standalone/nugu_sample.cc
  examples/standalone/nugu_sample_manager.cc
  examples/standalone/nugu_sample_manager.hh
  src/capability/asr_agent.cc
  src/core/audio_input_processor.cc
  src/core/speech_recognizer.cc
  src/core/speech_recognizer.hh
  src/core/wakeup_detector.cc
  src/core/wakeup_detector.hh
Labels: bug

#189 add suspend/restore command in nugu sample
  examples/standalone/nugu_sample.cc
  examples/standalone/nugu_sample_manager.cc
  examples/standalone/nugu_sample_manager.hh
Labels: enhancement

#190 base: add missing get_system() to log api
  include/base/nugu_log.h
  src/base/nugu_log.c
Labels: enhancement

#192 plugin: remove gst_deinit in gstreamer plugin
  plugins/gstreamer.c
Labels: bug

#193 clientkit: fix invalid destroy function
  src/clientkit/nugu_client_impl.cc
Labels: bug

#194 update play context policy
  include/clientkit/playsync_manager_interface.hh
  src/capability/asr_agent.cc
  src/capability/text_agent.cc
  src/core/capability_manager.cc
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
Labels: enhancement

#196 Implements capability suspend/restore
  examples/capability_injection/battery_agent.cc
  examples/capability_injection/battery_agent.hh
  examples/standalone/nugu_sample.cc
  include/clientkit/capability.hh
  include/clientkit/capability_interface.hh
  src/capability/asr_agent.cc
  src/capability/audio_player_agent.cc
  src/capability/tts_agent.cc
  src/clientkit/capability.cc
Labels: enhancement

#197 Refactoring: capability injection example
  examples/capability_injection/battery_agent.cc
  examples/capability_injection/battery_agent.hh
Labels: refactoring

#198 update TTSAgent suspend
  examples/standalone/nugu_sample.cc
  src/capability/tts_agent.cc
Labels: bug

#199 fix ASR stop unexpected issue
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
Labels: bug

#201 refactoring nugu sample adjust command
  examples/standalone/capability/speech_operator.cc
  examples/standalone/capability/speech_operator.hh
  examples/standalone/capability_collection.cc
  examples/standalone/capability_collection.hh
  examples/standalone/nugu_sample.cc
  examples/standalone/nugu_sample_manager.cc
  examples/standalone/nugu_sample_manager.hh
Labels: code quality, enhancement, refactoring

#202 Remove Warning
  examples/standalone/nugu_sample_manager.cc
  src/core/audio_recorder_manager.hh
Labels: code quality

#203 Optimization composing SpeakerInfo
  examples/standalone/capability_collection.cc
  examples/standalone/capability_collection.hh
  examples/standalone/nugu_sample_manager.cc
Labels: code quality
