Repository nugu-developers/nugu-linux, pull requests merged in 2020-06, with the labels that each got.

#349 NuguClient:Remove INetworkManagerListener inheritance
  src/clientkit/nugu_client_impl.cc
  src/clientkit/nugu_client_impl.hh
Labels: enhancement

#350 Test: Update build script
  tests/CMakeLists.txt
  tests/core-timer/CMakeLists.txt
  tests/core/CMakeLists.txt
  tests/core/test-core-nugu-timer-mock.cc
  tests/core/test-core-nugu-timer.cc
Labels: code quality

#352 pcm: add create/destroy ops to pcm driver
  include/base/nugu_pcm.h
  plugins/filedump.c
  plugins/portaudio.c
  src/base/nugu_pcm.c
  src/core/tts_player.cc
  tests/test-nugu-pcm.c
Labels: enhancement

#354 base: remove dirseq dependency from networkmanager
  include/base/nugu_directive.h
  include/base/nugu_directive_sequencer.h
  include/base/nugu_network_manager.h
  src/base/nugu_directive.c
  src/base/nugu_directive_sequencer.c
  src/base/nugu_network_manager.c
  src/clientkit/nugu_client_impl.cc
Labels: refactoring

#351 capability:Add Session Interface 1.0 skeleton
  examples/standalone/capability_collection.cc
  examples/standalone/capability_collection.hh
  examples/standalone/nugu_sample.cc
  include/capability/capability_factory.hh
  include/capability/session_interface.hh
  src/capability/capability_factory.cc
  src/capability/session_agent.cc
  src/capability/session_agent.hh
Labels: spec update

#355 Session: Add SessionManager
  include/clientkit/capability.hh
  include/clientkit/capability_helper_interface.hh
  include/clientkit/session_manager_interface.hh
  src/clientkit/capability.cc
  src/core/capability_helper.cc
  src/core/capability_helper.hh
  src/core/capability_manager.cc
  src/core/capability_manager.hh
  src/core/session_manager.cc
  src/core/session_manager.hh
Labels: enhancement

#328 base: fix driver custom data API naming
  include/base/nugu_decoder.h
  include/base/nugu_pcm.h
  include/base/nugu_player.h
  include/base/nugu_recorder.h
  plugins/filedump.c
  plugins/gstreamer.c
  plugins/opus.c
  plugins/portaudio.c
  src/base/nugu_decoder.c
  src/base/nugu_pcm.c
  src/base/nugu_player.c
  src/base/nugu_recorder.c
  tests/test-nugu-decoder.c
  tests/test-nugu-player.c
Labels: code quality

#346 ASRAgent: Update version 1.2
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
Labels: spec update

#347 TextAgent: Update version 1.2
  src/capability/text_agent.cc
Labels: spec update

#356 Session:Apply DM Session Flow
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/capability/session_agent.cc
Labels: enhancement, spec update

#358 ASR:Update ASR Interface version
  src/capability/asr_agent.cc
Labels: enhancement

#359 FocusManager: releaseFocus
  include/clientkit/focus_manager_interface.hh
  src/core/focus_manager.cc
  src/core/focus_manager.hh
  tests/core/test-core-focus-manager.cc
Labels: enhancement

#357 plugins: add file dump by environment variable
  CMakeLists.txt
  plugins/filedump.c
  plugins/opus.c
  plugins/portaudio.c
  src/core/tts_player.cc
Labels: enhancement

#363 Session:Change function name in SessionManager
  include/clientkit/session_manager_interface.hh
  src/capability/asr_agent.cc
  src/capability/session_agent.cc
  src/core/session_manager.cc
  src/core/session_manager.hh
Labels: enhancement

#364 Portaudio: Fix the bug
  plugins/portaudio.c
Labels: bug

#361 ASR:update ASR focus release
  include/clientkit/capability_helper_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/capability/text_agent.cc
  src/core/capability_helper.cc
  src/core/capability_helper.hh
  src/core/capability_manager.cc
  src/core/capability_manager.hh
Labels: enhancement

#360 FocusManager: Replace FocusManager
  include/base/nugu_focus.h
  include/clientkit/capability_helper_interface.hh
  src/base/nugu_focus.c
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
  src/capability/system_agent.cc
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
  src/core/capability_helper.cc
  src/core/capability_helper.hh
  src/core/capability_manager.cc
  src/core/capability_manager.hh
Labels: enhancement, refactoring

#365 Capability: Fix the hangup
  include/clientkit/capability.hh
  include/clientkit/capability_interface.hh
  include/clientkit/network_manager_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/clientkit/capability.cc
  src/clientkit/network_manager_interface.cc
  src/core/capability_manager.cc
  src/core/capability_manager.hh
Labels: bug

#362 core: introduce a new DirectiveSequencer
  include/base/nugu_directive_sequencer.h
  include/clientkit/capability.hh
  include/clientkit/capability_helper_interface.hh
  include/clientkit/directive_sequencer_interface.hh
  include/clientkit/nugu_core_container_interface.hh
  src/clientkit/capability.cc
  src/core/capability_helper.cc
  src/core/capability_helper.hh
  src/core/capability_manager.cc
  src/core/capability_manager.hh
  src/core/directive_sequencer.cc
  src/core/directive_sequencer.hh
  src/core/nugu_core_container.cc
  src/core/nugu_core_container.hh
  tests/core/CMakeLists.txt
  tests/core/test-core-directive-sequencer.cc
Labels: enhancement

#367 capability: apply new DirectiveSequencer
  include/base/nugu_directive_sequencer.h
  src/base/nugu_directive_sequencer.c
  src/capability/asr_agent.cc
  src/capability/audio_player_agent.cc
  src/capability/sound_agent.cc
  src/capability/sound_agent.hh
  src/capability/speaker_agent.cc
  src/capability/tts_agent.cc
  src/clientkit/capability.cc
  src/clientkit/nugu_client_impl.cc
  src/core/capability_manager.cc
  src/core/capability_manager.hh
Labels: enhancement

#369 capability: fix typo
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
Labels: code quality

#368 CapabilityManager: Optimize Code
  src/core/capability_manager.cc
  src/core/capability_manager.hh
Labels: code quality

#370 SpeakerAgent: Update version 1.1
  examples/standalone/capability_collection.cc
  include/capability/speaker_interface.hh
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
  src/capability/speaker_agent.cc
  src/capability/speaker_agent.hh
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
Labels: spec update

#371 AudioPlayerAgent: Change media content identification
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
Labels: spec update

#372 NuguClient:Remove getFocusManager in NuguClient
  examples/standalone/nugu_sample.cc
  include/clientkit/nugu_client.hh
  include/clientkit/nugu_core_container_interface.hh
  src/clientkit/nugu_client.cc
  src/clientkit/nugu_client_impl.cc
  src/clientkit/nugu_client_impl.hh
  src/core/nugu_core_container.cc
  src/core/nugu_core_container.hh
Labels: code quality

#374 profiling: add OPUS decoding for 1st attachment
  include/base/nugu_prof.h
  src/base/nugu_prof.c
  src/core/tts_player.cc
Labels: enhancement

#375 plugin: change PortAudio stream I/O method
  plugins/portaudio.c
Labels: enhancement

#376 Pcm: Export SetVolume to Driver
  include/base/nugu_pcm.h
  plugins/portaudio.c
  src/base/nugu_pcm.c
  src/capability/speaker_agent.cc
Labels: enhancement

#377 PlayStack: Add PlayStackManager
  include/clientkit/capability_helper_interface.hh
  include/clientkit/playstack_manager_interface.hh
  src/core/capability_helper.cc
  src/core/capability_helper.hh
  src/core/capability_manager.cc
  src/core/capability_manager.hh
  src/core/playstack_manager.cc
  src/core/playstack_manager.hh
  tests/core/CMakeLists.txt
  tests/core/test-core-playstack-manager.cc
Labels: enhancement, refactoring

#378 tts: set size limit for the 1st attachment
  include/base/nugu_directive.h
  src/base/nugu_directive.c
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
  src/core/tts_player.cc
  tests/test-nugu-directive.c
Labels: enhancement

#379 plugin: fix pcm playing status in portaudio
  plugins/portaudio.c
Labels: enhancement
