Repository nugu-developers/nugu-linux, pull requests merged in 2020-09, with the labels that each got.

#442 base: add Last-Asr-Event-Time HTTP header
  include/base/nugu_network_manager.h
  src/base/network/dg_server.c
  src/base/network/dg_server.h
  src/base/network/http2/http2_network.c
  src/base/network/http2/http2_network.h
  src/base/nugu_event.c
  src/base/nugu_network_manager.c
  tests/test_nugu_event.c
Labels: spec update

#444 playstack:update PlayStackManager
  include/clientkit/playstack_manager_interface.hh
  src/core/playstack_manager.cc
  src/core/playstack_manager.hh
Labels: enhancement

#445 capability: fix typo in the audio_player_agent
  include/capability/audio_player_interface.hh
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
Labels: code quality

#446 playsync:add PlaySyncManager
  include/clientkit/playsync_manager_interface.hh
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
  tests/core/CMakeLists.txt
  tests/core/test_core_playsync_manager.cc
Labels: enhancement

#408 Capability: add display interface
  examples/standalone/capability/audio_player_listener.cc
  examples/standalone/capability/audio_player_listener.hh
  include/capability/audio_player_interface.hh
  include/capability/display_interface.hh
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
Labels: enhancement

#447 playsync:add onDataChanged callback
  include/clientkit/playsync_manager_interface.hh
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
  tests/core/test_core_playsync_manager.cc
Labels: enhancement

#448 ASRAgent: Add asr error code
  src/capability/asr_agent.cc
Labels: enhancement

#449 examples: add scope and data information
  examples/oob_setup/nugu_oob_server.py
Labels: spec update

#451 SoundInterface:add DialogRequestId in handleBeep
  examples/standalone/capability/sound_listener.cc
  examples/standalone/capability/sound_listener.hh
  include/capability/sound_interface.hh
  src/capability/sound_agent.cc
Labels: enhancement

#450 playsync:apply PlaySyncManager in Capability Agents
  examples/standalone/capability_collection.cc
  include/clientkit/capability.hh
  include/clientkit/capability_helper_interface.hh
  include/clientkit/playstack_manager_interface.hh
  src/capability/asr_agent.cc
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
  src/capability/text_agent.cc
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
  src/clientkit/capability.cc
  src/core/capability_helper.cc
  src/core/capability_helper.hh
  src/core/capability_manager.cc
  src/core/capability_manager.hh
  src/core/playstack_manager.hh
Labels: enhancement

#452 Display:add DisplayAgent
  examples/standalone/capability/display_listener.cc
  examples/standalone/capability/display_listener.hh
  examples/standalone/capability_collection.cc
  examples/standalone/capability_collection.hh
  examples/standalone/nugu_sample.cc
  include/capability/capability_factory.hh
  src/capability/capability_factory.cc
  src/capability/display_agent.cc
  src/capability/display_agent.hh
Labels: enhancement, spec update

#453 AudioPlayer:fix sync data handling bug
  src/capability/audio_player_agent.cc
Labels: bug

#454 DisplayAgent: Update version 1.6
  src/capability/display_agent.cc
Labels: spec update

#455 tts:add condition not to handle sync release
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
Labels: enhancement

#456 AudioPlayer:update to manage render info to container
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
Labels: bug

#457 Text:update capability version to 1.3
  src/capability/text_agent.cc
  src/capability/text_agent.hh
Labels: code quality, spec update

#458 AudioPlayerAgent: Notify event
  src/capability/audio_player_agent.cc
Labels: bug

#459 text:apply default value on sendEventTextInput parameter
  src/capability/text_agent.cc
  src/capability/text_agent.hh
Labels: code quality

#460 nugu_sample:improve output log about display render
  examples/standalone/capability/audio_player_listener.cc
  examples/standalone/capability/display_listener.cc
Labels: code quality

#461 Display:update to refresh display render info
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
  src/capability/display_agent.cc
  src/capability/display_agent.hh
Labels: code quality, enhancement

#462 Text:add token parameter on requestTextInput
  examples/standalone/nugu_sample_manager.cc
  include/capability/text_interface.hh
  src/capability/text_agent.cc
  src/capability/text_agent.hh
Labels: spec update

#463 interaction:notify whether directive has multi-turn
  examples/standalone/nugu_sample.cc
  include/clientkit/interaction_control_manager_interface.hh
  src/core/capability_manager.cc
  src/core/interaction_control_manager.cc
  src/core/interaction_control_manager.hh
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
  tests/core/test_core_interaction_control_manager.cc
  tests/core/test_core_playsync_manager.cc
Labels: enhancement

#464 sample:refactoring nugu sample
  examples/standalone/capability/speech_operator.hh
  examples/standalone/nugu_sample.cc
  examples/standalone/nugu_sample_manager.cc
  examples/standalone/nugu_sample_manager.hh
  examples/standalone/nugu_sdk_manager.cc
  examples/standalone/nugu_sdk_manager.hh
Labels: enhancement, refactoring

#465 sample:update for compatibility about build environment
  examples/standalone/nugu_sample_manager.cc
Labels: enhancement
