Repository nugu-developers/nugu-linux, pull requests merged in 2021-05, with the labels that each got.

#606 PlaySync:Add release sync API
  include/clientkit/playsync_manager_interface.hh
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
  tests/core/test_core_playsync_manager.cc
Labels: enhancement

#608 base: add missing const to directive APIs
  include/base/nugu_directive.h
  src/base/nugu_directive.c
Labels: bug

#607 Routine:Add RoutineManager
  include/clientkit/capability_helper_interface.hh
  include/clientkit/routine_manager_interface.hh
  src/core/capability_helper.cc
  src/core/capability_helper.hh
  src/core/capability_manager.cc
  src/core/capability_manager.hh
  src/core/routine_manager.cc
  src/core/routine_manager.hh
  tests/core/CMakeLists.txt
  tests/core/test_core_routine_manager.cc
Labels: enhancement

#405 Routine:Add RoutinAgent
  examples/standalone/capability_collection.cc
  examples/standalone/capability_collection.hh
  examples/standalone/nugu_sdk_manager.cc
  include/capability/capability_factory.hh
  include/capability/routine_interface.hh
  include/clientkit/capability.hh
  src/capability/asr_agent.cc
  src/capability/audio_player_agent.cc
  src/capability/capability_factory.cc
  src/capability/routine_agent.cc
  src/capability/routine_agent.hh
  src/capability/text_agent.cc
  src/capability/text_agent.hh
  src/capability/tts_agent.cc
  src/clientkit/capability.cc
Labels: spec update

#609 Routine:Update stop condition
  src/capability/audio_player_agent.cc
  src/core/routine_manager.cc
  src/core/routine_manager.hh
  tests/core/test_core_routine_manager.cc
Labels: enhancement

#610 Text:Refactor requestTextInput methods
  src/capability/text_agent.cc
  src/capability/text_agent.hh
Labels: refactoring

#611 context:remove unnecessary context info about Routine
  src/core/capability_manager.cc
Labels: enhancement

#612 nugu_sample:Fix bug about constructing capability
  examples/standalone/capability_collection.hh
Labels: bug

#613 CapabilityManager:refactor composing context info
  include/clientkit/capability.hh
  include/clientkit/capability_interface.hh
  src/clientkit/capability.cc
  src/core/capability_manager.cc
  src/core/capability_manager.hh
Labels: refactoring

#614 TextAgent:change handling TextRedirect directive
  src/capability/text_agent.cc
Labels: bug

#615 TextAgent:Apply focus in sending TextInput event
  src/capability/asr_agent.cc
  src/capability/text_agent.cc
  src/capability/text_agent.hh
Labels: bug

#616 oob_server:Add OAuth2 client credentials
  examples/oob_setup/nugu_oob_server.py
Labels: enhancement

#617 Mic:adjust send SetMicSucceeded event
  src/capability/mic_agent.cc
Labels: bug, enhancement

#618 TTS:fix handling TTS.Stop directive
  src/capability/tts_agent.cc
Labels: bug

#627 Nudge:fix typo error
  src/capability/nudge_agent.cc
  src/capability/nudge_agent.hh
Labels: bug

#628 System:adjust access specifier
  src/capability/system_agent.hh
Labels: refactoring

#629 Text:adjust access specifier and method order
  src/capability/text_agent.cc
  src/capability/text_agent.hh
Labels: refactoring

#630 Display:adjust access specifier and method order
  src/capability/display_agent.cc
  src/capability/display_agent.hh
Labels: refactoring

#631 TTS:adjust access specifier and method order
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
Labels: refactoring

#632 AudioPlayer:adjust access specifier and method order
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
Labels: refactoring

#634 ASR:adjust access specifier and method order
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
Labels: refactoring

#633 AudioPlayerAgent: modified suspend (pause policy)
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
Labels: enhancement

#636 AudioPlayer:update condition to skip intermediate foreground focus
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
Labels: bug

#635 focus:add convertToFocusState in IFocusManager
  include/clientkit/focus_manager_interface.hh
  src/capability/text_agent.cc
  src/capability/tts_agent.cc
  src/core/focus_manager.cc
  src/core/focus_manager.hh
  tests/core/test_core_focus_manager.cc
Labels: refactoring

#637 AudioPlayerAgent: fix the bug
  src/capability/audio_player_agent.cc
Labels: bug

#638 AudioPlayerAgent: fix the bug
  src/capability/audio_player_agent.cc
Labels: bug

#640 AudioPlayerAgent: hold pause event
  examples/standalone/capability/audio_player_listener.cc
  include/capability/audio_player_interface.hh
  src/capability/audio_player_agent.cc
Labels: enhancement

#641 playsync:update releaseSyncImmediately condition
  src/core/playsync_manager.cc
Labels: enhancement

#639 Audioplayer direct control
  include/capability/audio_player_interface.hh
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
Labels: enhancement

#642 AudioPlayerAgent: add pause reason
  examples/standalone/capability/audio_player_listener.cc
  include/capability/audio_player_interface.hh
  src/capability/audio_player_agent.cc
Labels: enhancement

#643 TTS:update TTS playsync release
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
Labels: enhancement
