Repository nugu-developers/nugu-linux, pull requests merged in 2021-07, with the labels that each got.

#658 Capability: Display interface v1.8
  include/capability/display_interface.hh
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
  src/capability/display_agent.cc
  src/capability/display_agent.hh
Labels: enhancement

#659 TextAgent: Fixed the bug
  src/capability/text_agent.cc
Labels: bug

#660 Routine:apply schedule routine feature
  include/capability/routine_interface.hh
  src/capability/routine_agent.cc
  src/capability/routine_agent.hh
Labels: enhancement

#661 capability: add cancel option to stopRecognition
  examples/standalone/capability/speech_operator.cc
  examples/standalone/capability/speech_operator.hh
  examples/standalone/nugu_sdk_manager.cc
  include/capability/asr_interface.hh
  include/clientkit/directive_sequencer_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/core/directive_sequencer.cc
  src/core/directive_sequencer.hh
  tests/core/test_core_directive_sequencer.cc
Labels: enhancement

#662 capability: add check for canceled dialog-id
  include/clientkit/directive_sequencer_interface.hh
  src/capability/audio_player_agent.cc
  src/core/directive_sequencer.cc
  src/core/directive_sequencer.hh
Labels: enhancement

#663 TTS:update parsing TTS.Speak directive
  src/capability/tts_agent.cc
Labels: enhancement

#664 Playsync:fix PlaySyncManager test typo error
  tests/core/test_core_playsync_manager.cc
Labels: bug

#666 base: remove unused http2 network API
  src/base/network/http2/http2_network.c
  src/base/network/http2/http2_network.h
Labels: code quality

#667 TTS:fix parsing TTS.Speak directive
  src/capability/tts_agent.cc
Labels: bug

#668 TTS:remove unused variable
  src/capability/tts_agent.cc
Labels: code quality

#669 base: add request_id to manage http2 requests
  src/base/network/http2/http2_network.c
  src/base/network/http2/http2_network.h
  src/base/network/http2/http2_request.c
  src/base/network/http2/http2_request.h
  src/base/network/http2/v2_events.c
Labels: bug

#671 TTS:Add TTS speech STOP state
  examples/standalone/capability/tts_listener.cc
  include/capability/tts_interface.hh
  src/capability/tts_agent.cc
Labels: enhancement

#670 network: add FAILED error status
  examples/capability_injection/main_capability_injection.cc
  examples/profiling/main_prof.cc
  examples/response_filter/main.cc
  examples/simple_asr/main_asr.cc
  examples/simple_text/main_text.cc
  examples/simple_tts/main_tts.cc
  examples/standalone/nugu_sdk_manager.cc
  include/base/nugu_network_manager.h
  include/clientkit/network_manager_interface.hh
  src/base/nugu_network_manager.c
  src/core/network_manager.cc
Labels: enhancement

#672 TTS:refactor sending speech state event
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
Labels: refactoring

#665 PlaySync:update PlaySyncManager prepareSync
  include/clientkit/playsync_manager_interface.hh
  src/capability/display_render_helper.cc
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
  tests/core/test_core_playsync_manager.cc
Labels: enhancement

#674 Capability:Update directive cancel policy API
  include/clientkit/capability.hh
  include/clientkit/capability_interface.hh
  src/clientkit/capability.cc
  tests/CMakeLists.txt
  tests/clientkit/CMakeLists.txt
  tests/clientkit/test_clientkit_capability.cc
Labels: enhancement
