Repository nugu-developers/nugu-linux, pull requests merged in 2021-08, with the labels that each got.

#675 PlaySync:Add adjustPlayStackHoldTime API
  include/clientkit/playsync_manager_interface.hh
  src/core/playstack_manager.cc
  src/core/playstack_manager.hh
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
  tests/core/test_core_playstack_manager.cc
  tests/core/test_core_playsync_manager.cc
Labels: enhancement

#676 Display:Apply Display Duration Option
  src/capability/display_agent.cc
  src/capability/display_agent.hh
Labels: enhancement

#678 plugin: gstreamer recorder
  CMakeLists.txt
  plugins/CMakeLists.txt
  plugins/gstreamer_recorder.c
  plugins/portaudio_recorder.c
Labels: enhancement

#679 AudioPlayer:Update to handle display close by app
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
Labels: enhancement

#680 plugin: change the gstreamer sink
  plugins/gstreamer_pcm.c
Labels: enhancement

#681 PlaySync:Add restartHolding API
  include/clientkit/playsync_manager_interface.hh
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
  tests/core/test_core_playsync_manager.cc
Labels: enhancement

#682 Display:Add refreshRenderingTimer API
  include/capability/display_interface.hh
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
  src/capability/display_agent.cc
  src/capability/display_agent.hh
Labels: enhancement

#683 Display:Implements stopRenderingTimer
  src/capability/display_agent.cc
  tests/core/test_core_playsync_manager.cc
Labels: enhancement

#684 focus: focus hold
  src/core/focus_manager.cc
  tests/core/test_core_focus_manager.cc
Labels: enhancement

#685 PlaySync:Add setDefaultPlayStackHoldTime API
  include/clientkit/playsync_manager_interface.hh
  src/core/playstack_manager.cc
  src/core/playstack_manager.hh
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
  tests/core/test_core_playstack_manager.cc
  tests/core/test_core_playsync_manager.cc
Labels: enhancement

#686 PlaySync:Fix PlayStack Holding in Media Paused
  src/capability/display_agent.cc
  src/core/playstack_manager.cc
  src/core/playsync_manager.cc
  tests/core/test_core_playsync_manager.cc
Labels: bug

#687 core: add directive find API to sequencer
  include/clientkit/directive_sequencer_interface.hh
  src/core/directive_sequencer.cc
  src/core/directive_sequencer.hh
  tests/core/test_core_directive_sequencer.cc
Labels: enhancement

#656 Capability: Add PhoneCall interface v1.2
  include/capability/capability_factory.hh
  include/capability/phone_call_interface.hh
  src/capability/capability_factory.cc
  src/capability/phone_call_agent.cc
  src/capability/phone_call_agent.hh
Labels: spec update

#689 Playsync:clean PlaySyncManager test code
  tests/core/test_core_playsync_manager.cc
Labels: code quality

#688 TTS: apply destroy directive by agent option
  src/capability/tts_agent.cc
Labels: enhancement

#690 AudioPlayer:refactor AudioPlayer Display Interface
  examples/standalone/capability/audio_player_listener.hh
  examples/standalone/capability_collection.cc
  include/capability/audio_player_interface.hh
  include/capability/display_interface.hh
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
  src/capability/display_agent.cc
  src/capability/display_agent.hh
  src/capability/display_interface.cc
Labels: refactoring

#691 AudioPlayer:update to handle directives about Lyrics
  examples/standalone/capability/audio_player_listener.cc
  examples/standalone/capability/audio_player_listener.hh
  src/capability/audio_player_agent.cc
Labels: enhancement

#654 Capabiliy: Add Message interface v1.5
  include/capability/capability_factory.hh
  include/capability/message_interface.hh
  src/capability/capability_factory.cc
  src/capability/message_agent.cc
  src/capability/message_agent.hh
Labels: enhancement, spec update
