Repository nugu-developers/nugu-linux, pull requests merged in 2021-02, with the labels that each got.

#560 plugin:add option for selecting pcm plugin
  CMakeLists.txt
  plugins/CMakeLists.txt
Labels: enhancement

#561 nugu_sample:Add SpeakerStatus object
  examples/standalone/CMakeLists.txt
  examples/standalone/capability/mic_listener.cc
  examples/standalone/capability/speaker_listener.cc
  examples/standalone/nugu_sample_manager.cc
  examples/standalone/nugu_sample_manager.hh
  examples/standalone/nugu_sdk_manager.cc
  examples/standalone/nugu_sdk_manager.hh
  examples/standalone/speaker_status.cc
  examples/standalone/speaker_status.hh
  src/capability/audio_player_agent.cc
Labels: enhancement

#562 MicAgent:clean code about checking status
  src/capability/mic_agent.cc
  src/capability/mic_agent.hh
Labels: code quality, refactoring

#564 nugu_sample:add speaker volume/mute control
  examples/standalone/nugu_sdk_manager.cc
  examples/standalone/nugu_sdk_manager.hh
Labels: enhancement

#566 MediaPlayer:supplement media player mute
  src/core/media_player.cc
Labels: bug

#568 examples: fix url issue in nugu_oob_server.py
  examples/oob_setup/nugu_oob_server.py
Labels: bug

#569 Focus: modified focus holder
  src/core/focus_manager.cc
  src/core/focus_manager.hh
  tests/core/test_core_focus_manager.cc
Labels: bug

#570 AudioPlayer:set AudioPlayer/Display listener at once
  examples/standalone/capability_collection.cc
  src/capability/audio_player_agent.cc
Labels: enhancement
