Repository nugu-developers/nugu-linux, pull requests merged in 2021-03, with the labels that each got.

#571 ASR:apply ASR interface v1.5
  examples/response_filter/main.cc
  examples/simple_asr/main_asr.cc
  examples/standalone/capability/speech_operator.cc
  examples/standalone/capability/speech_operator.hh
  include/capability/asr_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
Labels: spec update

#572 AudioPlayer:apply AudioPlayer Interface v1.6
  src/capability/audio_player_agent.cc
Labels: spec update

#573 plugin:adjust build option about pcm plugin
  CMakeLists.txt
  plugins/CMakeLists.txt
Labels: enhancement

#574 capability:optimize method specifier and smart pointer usage
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
  src/capability/display_agent.cc
  src/capability/display_agent.hh
  src/capability/display_render_helper.cc
  src/capability/display_render_helper.hh
  src/capability/speaker_agent.cc
  src/capability/speaker_agent.hh
  src/capability/text_agent.cc
  src/core/capability_manager.cc
  src/core/capability_manager.hh
  src/core/playstack_manager.cc
  src/core/playstack_manager.hh
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
Labels: refactoring

#575 ASRAgent:fix handling ASR Initiator about EXPECT_SPEECH
  src/capability/asr_agent.cc
Labels: bug

#576 AudioPlayer:update parsing stop directive
  src/capability/audio_player_agent.cc
Labels: enhancement

#577 AudioPlayer: Block repeat playback of media content
  src/capability/audio_player_agent.cc
Labels: bug

#578 AudioPlayer: doesn't play the expired media
  .gitignore
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
Labels: bug

#579 Text: multi-turn
  src/capability/text_agent.cc
Labels: bug

#581 nugu_sample:optimize CapabilityCollection
  examples/standalone/capability_collection.cc
  examples/standalone/capability_collection.hh
Labels: refactoring

#583 Plugins: Added environment
  CMakeLists.txt
  src/base/nugu_plugin.c
Labels: enhancement

#584 Focus: fixed the recursive call bug
  src/core/focus_manager.cc
Labels: bug
