Repository nugu-developers/nugu-linux, pull requests merged in 2021-01, with the labels that each got.

#546 extension:match extension interface API
  examples/standalone/capability/extension_listener.cc
  examples/standalone/capability/extension_listener.hh
  include/capability/extension_interface.hh
  src/capability/extension_agent.cc
  src/capability/extension_agent.hh
Labels: code quality, enhancement

#543 capability:add setCancelPolicy API
  include/clientkit/capability.hh
  include/clientkit/capability_interface.hh
  src/clientkit/capability.cc
Labels: enhancement

#547 nugu_sample:show mic status on UI
  examples/standalone/nugu_sample_manager.cc
  examples/standalone/nugu_sample_manager.hh
  examples/standalone/nugu_sdk_manager.cc
  examples/standalone/nugu_sdk_manager.hh
Labels: enhancement, refactoring

#548 core: add cancel by group to directive sequencer
  include/clientkit/directive_sequencer_interface.hh
  src/core/directive_sequencer.cc
  src/core/directive_sequencer.hh
  tests/core/test_core_directive_sequencer.cc
Labels: enhancement

#549 action:update clang-tidy action usage
  .github/workflows/pull_request.yaml
Labels: ci/cd

#550 context:change context scope of some events
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
  src/capability/display_agent.cc
Labels: enhancement

#545 Log: Fixed formatter for pid
  src/base/nugu_log.c
Labels: bug

#551 playsync:add clear holding when preparing sync
  src/core/playsync_manager.cc
Labels: bug

#552 core: improves log readability of sequencer
  src/core/directive_sequencer.cc
  tests/core/test_core_directive_sequencer.cc
Labels: code quality

#553 Capability:apply partial cancel directives
  src/clientkit/capability.cc
Labels: enhancement

#554 playstack:change playstack layer terms to activity
  include/clientkit/playsync_manager_interface.hh
  src/capability/audio_player_agent.cc
  src/capability/tts_agent.cc
  src/core/playstack_manager.cc
  src/core/playstack_manager.hh
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
  tests/core/test_core_playstack_manager.cc
  tests/core/test_core_playsync_manager.cc
Labels: enhancement

#555 TTS:update handling TTS.Stop
  src/capability/tts_agent.cc
Labels: enhancement

#556 capability: apply json minify
  src/base/nugu_event.c
  src/capability/asr_agent.cc
  src/capability/audio_player_agent.cc
  src/capability/display_agent.cc
  src/capability/extension_agent.cc
  src/capability/mic_agent.cc
  src/capability/sound_agent.cc
  src/capability/speaker_agent.cc
  src/capability/text_agent.cc
  src/capability/tts_agent.cc
  src/core/capability_manager.cc
Labels: enhancement

#557 base: apply nugu sdk multipart rule
  src/base/network/http2/v2_events.c
Labels: enhancement

#558 TextAgent:handle TextRedirect by InteractionControl
  include/clientkit/interaction_control_manager_interface.hh
  src/capability/audio_player_agent.cc
  src/capability/text_agent.cc
  src/capability/text_agent.hh
  src/core/interaction_control_manager.cc
  src/core/interaction_control_manager.hh
  tests/core/test_core_interaction_control_manager.cc
Labels: enhancement

#559 base: fix send timing for 1st multipart boundary
  src/base/network/http2/v2_events.c
Labels: enhancement
