Repository nugu-developers/nugu-linux, pull requests merged in 2021-12, with the labels that each got.

#742 fix double free on cancelDirective
  src/capability/tts_agent.cc
  src/core/directive_sequencer.cc
Labels: bug

#746 Text:Apply Text interface v1.6
  src/capability/text_agent.cc
  src/capability/text_agent.hh
Labels: spec update

#747 base: add null check to plugin_find
  src/base/nugu_plugin.c
Labels: bug

#748 examples: fix model path
  examples/profiling/README.md
  examples/profiling/main_prof.cc
  examples/response_filter/main.cc
  examples/simple_asr/main_asr.cc
Labels: code quality

#749 Display:Apply InteractionControl in ControlScroll
  src/capability/display_agent.cc
  src/capability/display_agent.hh
Labels: enhancement

#750 Message:Update to finish InteractionControl
  src/capability/message_agent.cc
  src/capability/message_agent.hh
Labels: bug

#752 TTS:Fix playStackControl management
  src/capability/tts_agent.cc
Labels: bug

#751 fix last attachment data for ASR
  include/clientkit/speech_recognizer_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/core/speech_recognizer.cc
Labels: enhancement

#754 Fix Cppcheck analysis results
  .cppcheck_suppress.txt
  examples/capability_injection/battery_agent.hh
  examples/standalone/capability/display_listener.cc
  examples/standalone/capability/sound_listener.hh
  examples/standalone/nugu_sample_manager.cc
  include/clientkit/capability.hh
  src/capability/asr_agent.cc
  src/capability/audio_player_agent.cc
  src/capability/routine_agent.cc
  src/capability/session_agent.hh
  src/clientkit/nugu_client.cc
  src/core/audio_recorder_manager.cc
  src/core/audio_recorder_manager.hh
  src/core/capability_manager.cc
  src/core/capability_manager.hh
  src/core/directive_sequencer.cc
  src/core/playstack_manager.hh
  src/core/speech_recognizer.hh
  src/core/wakeup_detector.hh
  tests/core/test_core_playstack_manager.cc
Labels: code quality

#757 examples:Add override keyword
  examples/capability_injection/main_capability_injection.cc
  examples/profiling/main_prof.cc
  examples/response_filter/filter.cc
  examples/response_filter/main.cc
  examples/simple_asr/main_asr.cc
  examples/simple_play/main_play.cc
  examples/simple_text/main_text.cc
  examples/simple_tts/main_tts.cc
Labels: code quality

#756 plugin: add OPUS encoder plugin
  CMakeLists.txt
  plugins/CMakeLists.txt
  plugins/opus.c
  plugins/opus_encoder.c
Labels: enhancement

#761 plugins: adjust pcm driver priority
  plugins/gstreamer.c
  plugins/portaudio.c
  plugins/portaudio_pcm_async.c
  plugins/portaudio_pcm_sync.c
  plugins/portaudio_recorder.c
Labels: enhancement

#762 plugins: fix gstreamer pcm pipeline
  plugins/gstreamer_pcm.c
Labels: bug

#765 nugu_sample:Add getCapabilityListener in CapabilityCollection
  examples/standalone/capability_collection.cc
  examples/standalone/capability_collection.hh
Labels: enhancement

#763 plugins: add dump feature to gstreamer recorder
  plugins/gstreamer_recorder.c
Labels: enhancement

#766 nugu_sample:Refactor SpeakerController setup
  examples/standalone/capability/speaker_listener.cc
  examples/standalone/capability/speaker_listener.hh
  examples/standalone/nugu_sdk_manager.cc
  examples/standalone/nugu_sdk_manager.hh
Labels: refactoring

#767 nugu_sample:Handle TTS mute
  examples/standalone/capability_collection.cc
  examples/standalone/nugu_sdk_manager.cc
  examples/standalone/nugu_sdk_manager.hh
Labels: enhancement

#768 examples: add type2 authentication support
  examples/capability_injection/main_capability_injection.cc
  examples/profiling/main_prof.cc
  examples/response_filter/main.cc
  examples/simple_asr/main_asr.cc
  examples/simple_text/main_text.cc
  examples/simple_tts/main_tts.cc
Labels: enhancement

#769 nugu_sample:Refactor composing capability factory
  examples/standalone/capability_collection.cc
  examples/standalone/capability_collection.hh
Labels: refactoring

#764 Text:Update Text Interface 1.6 spec
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/capability/text_agent.cc
  src/capability/text_agent.hh
Labels: spec update

#771 Capability: Modified Context
  examples/standalone/capability/bluetooth_listener.cc
  examples/standalone/capability/bluetooth_listener.hh
  examples/standalone/capability/extension_listener.cc
  examples/standalone/capability/extension_listener.hh
  examples/standalone/nugu_sdk_manager.cc
  include/capability/bluetooth_interface.hh
  include/capability/extension_interface.hh
  src/capability/bluetooth_agent.cc
  src/capability/bluetooth_agent.hh
  src/capability/extension_agent.cc
  src/capability/extension_agent.hh
Labels: refactoring
