Repository nugu-developers/nugu-linux, pull requests merged in 2021-09, with the labels that each got.

#698 core: add input/output type to epd_param
  src/core/speech_recognizer.cc
Labels: enhancement

#699 fix build status badge
  README.md
Labels: documentation

#700 Routine:Update check about finishing action
  include/clientkit/routine_manager_interface.hh
  src/clientkit/capability.cc
  src/core/routine_manager.cc
  src/core/routine_manager.hh
  tests/core/test_core_routine_manager.cc
Labels: enhancement

#702 Message: added playback state event
  include/capability/message_interface.hh
  src/capability/message_agent.cc
  src/capability/message_agent.hh
Labels: enhancement

#704 PhoneCall: modified CallEstablished
  src/capability/phone_call_agent.cc
Labels: bug

#706 base: add encoder driver
  include/base/nugu_encoder.h
  src/base/nugu_decoder.c
  src/base/nugu_encoder.c
  tests/CMakeLists.txt
  tests/test_nugu_encoder.c
Labels: enhancement

#708 fix static analysis tool report issues
  examples/oob_setup/nugu_oob_server.py
  examples/standalone/nugu_sample_manager.hh
  plugins/gstreamer_pcm.c
  src/base/network/http2/v1_ping.c
  src/base/nugu_network_manager.c
Labels: code quality

#710 Plugins: Modified the gstreamer pcm
  plugins/gstreamer_pcm.c
Labels: bug

#711 TTS:Add setMute API
  include/capability/tts_interface.hh
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
Labels: enhancement

#712 packaging: add ubuntu 20.04(focal)
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  packaging/focal/changelog
  packaging/focal/compat
  packaging/focal/control
  packaging/focal/copyright
  packaging/focal/libnugu-dev.install
  packaging/focal/libnugu-examples.install
  packaging/focal/libnugu-examples.lintian-overrides
  packaging/focal/libnugu-plugins-default.install
  packaging/focal/libnugu-plugins-default.lintian-overrides
  packaging/focal/libnugu.install
  packaging/focal/libnugu.lintian-overrides
  packaging/focal/rules
  packaging/focal/source/format
  packaging/focal/source/lintian-overrides
Labels: ci/cd

#714 build: enhance __FILE__ macro
  CMakeLists.txt
Labels: code quality

#713 Build: support to build Ninja
  externals/CMakeLists.txt
Labels: enhancement

#715 build: add CMAKE_GENERATOR guard to filename macro
  CMakeLists.txt
Labels: ci/cd/build
