Repository nugu-developers/nugu-linux, pull requests merged in 2021-06, with the labels that each got.

#644 CapabilityManager:Improve efficiency onHandleDirective
  src/core/capability_manager.cc
  src/core/capability_manager.hh
Labels: enhancement

#626 Asset:Add EPD/KWD model files
  CMakeLists.txt
  assets/model/skt_epd_model.raw
  assets/model/skt_trigger_am_aria.raw
  assets/model/skt_trigger_am_tinkerbell.raw
  assets/model/skt_trigger_search_aria.raw
  assets/model/skt_trigger_search_tinkerbell.raw
  examples/standalone/capability/speech_operator.cc
  examples/standalone/capability/speech_operator.hh
  examples/standalone/nugu_sample_manager.cc
  examples/standalone/nugu_sample_manager.hh
  examples/standalone/nugu_sdk_manager.cc
  examples/standalone/nugu_sdk_manager.hh
  include/clientkit/nugu_core_container_interface.hh
  include/clientkit/wakeup_interface.hh
  packaging/bionic/libnugu.install
  packaging/xenial/libnugu.install
  src/core/nugu_core_container.cc
  src/core/nugu_core_container.hh
  src/core/speech_recognizer.hh
  src/core/wakeup_detector.cc
  src/core/wakeup_detector.hh
  src/core/wakeup_handler.cc
  src/core/wakeup_handler.hh
Labels: enhancement

#645 AudioPlayer:add to send LOAD_DONE media event
  src/capability/audio_player_agent.cc
Labels: enhancement

#646 nugu_sample:adjust NuguSDKManager creation order
  examples/standalone/nugu_sample.cc
Labels: bug

#647 Document:update README
  README.md
Labels: documentation

#648 packaging:fix libnugu and libnugu-example install
  packaging/bionic/libnugu-examples.install
  packaging/bionic/libnugu.install
  packaging/xenial/libnugu-examples.install
  packaging/xenial/libnugu.install
Labels: bug

#650 AudioPlayerAgent: sync with context
  src/capability/audio_player_agent.cc
Labels: bug

#651 AudioPlayerAgent: fix the bug
  src/capability/audio_player_agent.cc
Labels: bug

#652 capability: fix SKML empty string check logic
  src/capability/tts_agent.cc
Labels: bug

#653 CapabilityManager:Handle Network Disconnected Status
  src/capability/audio_player_agent.cc
  src/core/capability_manager.cc
  src/core/capability_manager.hh
Labels: enhancement

#655 PlaySyncManager:Add onStackChanged API in IPlaySyncManagerListener
  include/clientkit/playsync_manager_interface.hh
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
  src/clientkit/playsync_manager_interface.cc
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
  tests/core/test_core_playsync_manager.cc
Labels: enhancement, refactoring
