Repository nugu-developers/nugu-linux, pull requests merged in 2021-11, with the labels that each got.

#735 Display:Update handling history control
  src/capability/display_agent.cc
  src/capability/display_agent.hh
  src/capability/display_render_helper.cc
  src/capability/display_render_helper.hh
Labels: enhancement

#738 Capability: Bluetooth interface v1.1
  examples/standalone/bluetooth_status.cc
  examples/standalone/bluetooth_status.hh
  examples/standalone/capability/bluetooth_listener.cc
  examples/standalone/capability/bluetooth_listener.hh
  examples/standalone/capability_collection.cc
  examples/standalone/capability_collection.hh
  examples/standalone/nugu_sdk_manager.cc
  examples/standalone/nugu_sdk_manager.hh
  include/capability/bluetooth_interface.hh
  include/capability/capability_factory.hh
  src/capability/bluetooth_agent.cc
  src/capability/bluetooth_agent.hh
  src/capability/capability_factory.cc
Labels: enhancement, spec update

#737 fix static analysis tool report issues
  include/clientkit/capability.hh
Labels: code quality

#739 add cppcheck tool to pull_request action
  .cppcheck_suppress.txt
  .github/workflows/pull_request.yaml
Labels: code quality, ci/cd/build

#740 PlaySync:Update releaseSyncUnconditionally API
  include/clientkit/playsync_manager_interface.hh
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
  tests/core/test_core_playsync_manager.cc
Labels: enhancement

#741 add cancelDirective to AudioPlayer
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
Labels: bug
