Repository nugu-developers/nugu-linux, pull requests merged in 2021-04, with the labels that each got.

#585 ASR:adjust handling ExpectSpeech
  src/capability/asr_agent.cc
  src/clientkit/capability.cc
Labels: enhancement

#586 PlaySync:Add clear API for removing playstack info
  include/clientkit/playsync_manager_interface.hh
  src/core/playsync_manager.cc
  src/core/playsync_manager.hh
  tests/core/test_core_playsync_manager.cc
Labels: enhancement

#587 AudioPlayerAgent: Fixed the version 1.5 spec
  src/capability/audio_player_agent.cc
  src/capability/audio_player_agent.hh
Labels: bug

#588 Display:Apply Display Interface v1.7
  src/capability/display_agent.cc
Labels: spec update

#589 Chips:Apply Chips Interface v1.2
  examples/standalone/capability/chips_listener.cc
  examples/standalone/capability/chips_listener.hh
  include/capability/chips_interface.hh
  src/capability/chips_agent.cc
  src/capability/chips_agent.hh
Labels: spec update

#590 AudioPlayer: fix command issue
  src/capability/audio_player_agent.cc
Labels: enhancement

#591 ASR:Apply ASR interface v1.6
  examples/profiling/main_prof.cc
  examples/response_filter/main.cc
  examples/simple_asr/main_asr.cc
  examples/standalone/capability/speech_operator.cc
  examples/standalone/capability/speech_operator.hh
  include/capability/asr_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
Labels: spec update

#592 TTS:Add add/remove Listener API
  include/capability/tts_interface.hh
  src/capability/tts_agent.cc
  src/capability/tts_agent.hh
Labels: enhancement

#593 [ASR,AudioPlayer] Change handling listeners in Range-based for loop
  src/capability/asr_agent.cc
  src/capability/audio_player_agent.cc
Labels: refactoring

#595 examples: remove oob systemd file from install
  examples/oob_setup/CMakeLists.txt
  packaging/bionic/libnugu-examples.install
  packaging/xenial/libnugu-examples.install
Labels: code quality

#594 network: add network connection type
  include/base/nugu_network_manager.h
  include/clientkit/network_manager_interface.hh
  src/base/nugu_network_manager.c
  src/core/network_manager.cc
Labels: enhancement

#597 network: remove event send with sync
  include/base/nugu_network_manager.h
  include/clientkit/capability.hh
  src/base/network/dg_server.c
  src/base/network/dg_server.h
  src/base/network/http2/v1_event.c
  src/base/network/http2/v1_event.h
  src/base/network/http2/v2_events.c
  src/base/network/http2/v2_events.h
  src/base/nugu_network_manager.c
  src/clientkit/capability.cc
Labels: code quality

#596 Fix out_of_range without header
  src/core/playstack_manager.cc
  src/core/playsync_manager.cc
Labels: bug

#598 Fix gcc-10 format-truncation warning
  plugins/filedump.c
  plugins/gstreamer_pcm.c
  plugins/opus.c
  plugins/portaudio_pcm_async.c
  plugins/portaudio_pcm_sync.c
  plugins/portaudio_recorder.c
Labels: bug

#599 network: add on-demand network type
  examples/standalone/nugu_sdk_manager.cc
  include/base/nugu_network_manager.h
  include/clientkit/network_manager_interface.hh
  src/base/nugu_network_manager.c
  src/core/network_manager.cc
Labels: enhancement

#600 add const to auto variables
  src/core/network_manager.cc
Labels: code quality

#601 Wakeup:Add API for changing model
  include/clientkit/wakeup_interface.hh
  src/core/wakeup_detector.cc
  src/core/wakeup_detector.hh
  src/core/wakeup_handler.cc
  src/core/wakeup_handler.hh
Labels: enhancement

#603 nugu_sample:Change shared_ptr to unique_ptr
  examples/standalone/nugu_sdk_manager.cc
  examples/standalone/nugu_sdk_manager.hh
Labels: refactoring

#604 NetworkManager:Apply const reference in method arguments
  include/clientkit/network_manager_interface.hh
  src/core/network_manager.cc
  src/core/network_manager.hh
Labels: refactoring

#605 AudioInputProcessor:Apply move semantics in method arguments
  src/core/audio_input_processor.cc
  src/core/audio_input_processor.hh
Labels: refactoring
