Repository nugu-developers/nugu-linux, pull requests merged in 2022-06, with the labels that each got.

#833 SpeechRecognizerAggregator: adjust validation check
  src/clientkit/speech_recognizer_aggregator.cc
  tests/clientkit/test_clientkit_speech_recognizer_aggregator.cc
Labels: enhancement

#834 plugins: fix memory leak of speex
  plugins/speex.c
Labels: bug

#836 plugins: fix memory leak of opus encoder
  plugins/opus_encoder.c
Labels: bug

#837 wakeup: add wakeup idle state
  examples/standalone/clientkit/speech_recognizer_aggregator_listener.cc
  include/clientkit/wakeup_interface.hh
  tests/clientkit/test_clientkit_speech_recognizer_aggregator.cc
Labels: enhancement

#841 wakeup: change handling wakeup stop state
  src/core/wakeup_detector.cc
  src/core/wakeup_detector.hh
  src/core/wakeup_handler.cc
Labels: enhancement

#842 build: fix link directory search order
  CMakeLists.txt
  examples/capability_injection/CMakeLists.txt
  examples/profiling/CMakeLists.txt
  examples/response_filter/CMakeLists.txt
  examples/simple_asr/CMakeLists.txt
  examples/simple_play/CMakeLists.txt
  examples/simple_text/CMakeLists.txt
  examples/simple_tts/CMakeLists.txt
  examples/standalone/CMakeLists.txt
  plugins/CMakeLists.txt
  tests/CMakeLists.txt
  tests/clientkit/CMakeLists.txt
  tests/core/CMakeLists.txt
Labels: ci/cd/build

#840 base: fix memory leak in http2 network module
  src/base/network/http2/http2_network.c
Labels: bug

#843 SpeechRecognizerAggregator: expose setWakeupHandler API
  include/clientkit/speech_recognizer_aggregator_interface.hh
  src/clientkit/nugu_client_impl.cc
  src/clientkit/speech_recognizer_aggregator.cc
  src/clientkit/speech_recognizer_aggregator.hh
  tests/clientkit/test_clientkit_speech_recognizer_aggregator.cc
Labels: enhancement

#845 build: remove xenial(16.04) target
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .travis.yml
  README.md
Labels: ci/cd/build

#846 build: apply LTO option
  CMakeLists.txt
Labels: ci/cd/build

#847 build:update cppcheck ubuntu target
  .github/workflows/pull_request.yaml
Labels: ci/cd/build

#848 examples: update nugu_oob_server
  examples/oob_setup/nugu_oob_server.py
  packaging/bionic/control
  packaging/focal/control
  packaging/jammy/control
Labels: enhancement

#852 upgrade clang-tidy-action to v1.2
  .github/workflows/pull_request.yaml
  examples/standalone/capability/tts_listener.cc
  examples/standalone/capability/tts_listener.hh
  examples/standalone/nugu_sdk_manager.cc
  src/capability/display_agent.cc
  src/capability/display_render_helper.cc
  src/capability/message_agent.cc
  src/core/audio_recorder_manager.cc
  src/core/focus_manager.cc
  tests/core/test_core_playsync_manager.cc
  tests/core/test_core_routine_manager.cc
Labels: ci/cd/build

#850 build: adjust LTO enable condition
  CMakeLists.txt
Labels: ci/cd/build

#853 build: add built-in option for curl
  CMakeLists.txt
  externals/CMakeLists.txt
  src/CMakeLists.txt
  src/base/CMakeLists.txt
Labels: ci/cd/build
