Repository nugu-developers/nugu-linux, pull requests merged in 2022-03, with the labels that each got.

#788 AudioPlayer:fix handling cancel directive
  src/capability/audio_player_agent.cc
  src/capability/display_agent.cc
  src/capability/display_agent.hh
Labels: bug

#789 Display:Fix handling history control
  src/capability/display_agent.cc
  src/capability/display_agent.hh
Labels: bug

#790 AudioPlayer:update PlayStackControl info management
  src/capability/audio_player_agent.cc
Labels: enhancement

#791 audio: add audio attribute
  include/base/nugu_audio.h
  include/base/nugu_pcm.h
  include/base/nugu_player.h
  include/clientkit/media_player_interface.hh
  src/base/nugu_audio.c
  src/base/nugu_pcm.c
  src/base/nugu_player.c
  src/capability/audio_player_agent.cc
  src/capability/tts_agent.cc
  src/core/media_player.cc
  src/core/media_player.hh
  src/core/tts_player.cc
  src/core/tts_player.hh
  tests/test_nugu_pcm.c
  tests/test_nugu_player.c
Labels: enhancement

#792 clientkit: fix the code convention
  include/clientkit/media_player_interface.hh
  src/capability/audio_player_agent.cc
  src/capability/message_agent.cc
  src/capability/tts_agent.cc
  src/core/tts_player.cc
  src/core/tts_player.hh
Labels: code quality

#795 Text:apply TextInput event latest spec
  examples/standalone/nugu_sdk_manager.cc
  include/capability/text_interface.hh
  src/capability/text_agent.cc
  src/capability/text_agent.hh
Labels: spec update

#796 plugin: add audio attribute
  CMakeLists.txt
  plugins/gstreamer.c
  plugins/gstreamer_pcm.c
Labels: enhancement

#797 speaker: sync with audio property
  examples/standalone/capability_collection.cc
  include/base/nugu_audio.h
  include/capability/speaker_interface.hh
  src/base/nugu_audio.c
  src/capability/speaker_agent.hh
Labels: code quality
