Repository nugu-developers/nugu-linux, pull requests merged in 2022-05, with the labels that each got.

#816 nugu_oob_server: add jti on result
  examples/oob_setup/nugu_oob_server.py
Labels: enhancement

#818 tests: fix http test case
  tests/test_nugu_http.c
Labels: ci/cd/build

#821 packaging: fix libasan version in 20.04(focal)
  packaging/focal/control
Labels: ci/cd/build

#822 build: enable ASAN on armhf/arm64 platform
  CMakeLists.txt
Labels: ci/cd/build

#823 clientkit: add SpeechRecognizerAggregator
  include/clientkit/speech_recognizer_aggregator_interface.hh
  src/clientkit/speech_recognizer_aggregator.cc
  src/clientkit/speech_recognizer_aggregator.hh
  tests/clientkit/CMakeLists.txt
  tests/clientkit/test_clientkit_speech_recognizer_aggregator.cc
Labels: enhancement

#824 NuguClient: compose SpeechRecognizerAggregator
  include/clientkit/nugu_client.hh
  src/clientkit/nugu_client.cc
  src/clientkit/nugu_client_impl.cc
  src/clientkit/nugu_client_impl.hh
Labels: enhancement

#825 examples: apply SpeechRecognizerAggregator in nugu_sample
  examples/standalone/CMakeLists.txt
  examples/standalone/capability/speech_operator.cc
  examples/standalone/capability/speech_operator.hh
  examples/standalone/capability_collection.cc
  examples/standalone/capability_collection.hh
  examples/standalone/clientkit/speech_recognizer_aggregator_listener.cc
  examples/standalone/clientkit/speech_recognizer_aggregator_listener.hh
  examples/standalone/nugu_sdk_manager.cc
  examples/standalone/nugu_sdk_manager.hh
Labels: enhancement

#826 SpeechRecognizerAggregator: change setWakeupModel return type
  include/clientkit/speech_recognizer_aggregator_interface.hh
  src/clientkit/speech_recognizer_aggregator.cc
  src/clientkit/speech_recognizer_aggregator.hh
  tests/clientkit/test_clientkit_speech_recognizer_aggregator.cc
Labels: enhancement

#829 clientkit: fix nugu_runner wait blocking issue
  src/clientkit/nugu_runner.cc
Labels: bug

#827 packaging: add ubuntu 22.04(jammy)
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  packaging/jammy/changelog
  packaging/jammy/compat
  packaging/jammy/control
  packaging/jammy/copyright
  packaging/jammy/libnugu-dev.install
  packaging/jammy/libnugu-examples.install
  packaging/jammy/libnugu-examples.lintian-overrides
  packaging/jammy/libnugu-plugins-default.install
  packaging/jammy/libnugu-plugins-default.lintian-overrides
  packaging/jammy/libnugu.install
  packaging/jammy/libnugu.lintian-overrides
  packaging/jammy/rules
  packaging/jammy/source/format
  packaging/jammy/source/lintian-overrides
Labels: ci/cd/build
