Repository nugu-developers/nugu-linux, pull requests merged in 2022-04, with the labels that each got.

#799 clientkit: expose focus manager interface
  include/clientkit/nugu_client.hh
  src/clientkit/nugu_client.cc
  src/clientkit/nugu_client_impl.cc
  src/clientkit/nugu_client_impl.hh
Labels: enhancement

#800 base: set audio property's name
  include/base/nugu_audio.h
  include/capability/speaker_interface.hh
  src/base/nugu_audio.c
  src/capability/speaker_agent.cc
  src/capability/speaker_agent.hh
  tests/CMakeLists.txt
  tests/test_nugu_audio.c
  tests/test_nugu_pcm.c
  tests/test_nugu_player.c
Labels: enhancement

#801 Chips:change onReceiveRender argument type
  examples/standalone/capability/chips_listener.cc
  examples/standalone/capability/chips_listener.hh
  include/capability/chips_interface.hh
  src/capability/chips_agent.cc
Labels: enhancement

#802 Chips:update to support multi listeners
  include/capability/chips_interface.hh
  src/capability/chips_agent.cc
  src/capability/chips_agent.hh
Labels: enhancement

#805 base: add byte buffer manipulation to nugu_buffer
  include/base/nugu_buffer.h
  src/base/nugu_buffer.c
  tests/test_nugu_buffer.c
Labels: enhancement

#806 clientkit: add DialogUXStateAggregator
  include/clientkit/dialog_ux_state_aggregator_interface.hh
  src/clientkit/dialog_ux_state_aggregator.cc
  src/clientkit/dialog_ux_state_aggregator.hh
  tests/clientkit/CMakeLists.txt
  tests/clientkit/test_clientkit_dialog_ux_state_aggregator.cc
Labels: enhancement

#808 DialogUXStateAggregator: fix handling chips info
  src/clientkit/dialog_ux_state_aggregator.cc
  tests/clientkit/test_clientkit_dialog_ux_state_aggregator.cc
Labels: bug

#812 ASR: fix DM focus release
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
Labels: bug

#813 ASR: refactor FocusListener
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
Labels: refactoring

#814 Text:update Text interface 1.7
  src/capability/text_agent.cc
Labels: spec update

#815 base: add HTTP download API
  include/base/nugu_http.h
  src/base/nugu_http.c
  tests/test_nugu_http.c
Labels: enhancement
