Repository nugu-developers/nugu-linux, pull requests merged in 2022-08, with the labels that each got.

#859 build: add CodeQL static analysis
  .github/workflows/codeql-analysis.yaml
Labels: code quality, ci/cd/build

#861 Text: add interactionControl in TextInput event
  src/capability/text_agent.cc
  src/capability/text_agent.hh
Labels: spec update

#862 Display: add interactionControl in response events
  src/capability/display_agent.cc
  src/capability/display_agent.hh
Labels: spec update

#863 build: apply debian packaging default link option
  CMakeLists.txt
Labels: ci/cd/build
