Repository nugu-developers/nugu-linux, pull requests merged in 2022-07, with the labels that each got.

#854 build: apply -fanalyzer compile option
  CMakeLists.txt
  include/base/nugu_plugin.h
  src/base/nugu_plugin.c
  tests/test_nugu_plugin.c
Labels: code quality

#855 ASR: apply ASR interface v1.7 spec
  src/capability/asr_agent.cc
Labels: spec update

#856 clientkit: add async API to auth discovery
  include/clientkit/nugu_auth.hh
  src/clientkit/nugu_auth.cc
  tests/clientkit/test_clientkit_auth.cc
Labels: enhancement

#857 gstreamer: disconnect signal
  plugins/gstreamer.c
  plugins/gstreamer_pcm.c
  plugins/gstreamer_recorder.c
Labels: bug
