Repository nugu-developers/nugu-linux, pull requests merged in 2022-09, with the labels that each got.

#866 add missing include to header files
  include/base/nugu_buffer.h
  include/base/nugu_directive.h
  include/base/nugu_pcm.h
  include/clientkit/routine_manager_interface.hh
  include/clientkit/wakeup_interface.hh
  src/base/network/http2/multipart_parser.h
  src/base/network/http2/v2_events.c
  src/base/network/http2/v2_events.h
  src/core/directive_sequencer.cc
  src/core/directive_sequencer.hh
Labels: code quality

#867 fix typo error
  include/clientkit/network_manager_interface.hh
  include/clientkit/nugu_runner.hh
  include/clientkit/playsync_manager_interface.hh
  src/base/network/dg_server.c
  src/base/network/dg_server.h
  src/base/nugu_network_manager.c
  src/capability/display_agent.cc
  src/capability/display_agent.hh
  src/clientkit/nugu_auth.cc
  src/clientkit/nugu_client_impl.cc
  src/core/nugu_core_container.cc
  src/core/nugu_core_container.hh
  src/core/playstack_manager.cc
  src/core/playstack_manager.hh
  src/core/playsync_manager.cc
  tests/clientkit/test_clientkit_capability.cc
  tests/clientkit/test_clientkit_nugu_runner.cc
  tests/core/test_core_focus_manager.cc
  tests/core/test_core_playstack_manager.cc
  tests/core/test_core_playsync_manager.cc
  tests/core/test_core_routine_manager.cc
  tests/test_nugu_player.c
Labels: code quality

#868 add tag name to anonymous structure
  include/capability/asr_interface.hh
  include/capability/battery_interface.hh
  include/capability/bluetooth_interface.hh
  include/capability/display_interface.hh
  include/capability/location_interface.hh
  include/capability/text_interface.hh
  include/capability/tts_interface.hh
  include/clientkit/capability_interface.hh
  include/clientkit/directive_sequencer_interface.hh
  include/clientkit/focus_manager_interface.hh
  include/clientkit/session_manager_interface.hh
  include/clientkit/speech_recognizer_aggregator_interface.hh
  include/clientkit/speech_recognizer_interface.hh
  include/clientkit/wakeup_interface.hh
  src/capability/display_agent.hh
  src/capability/display_render_helper.hh
  src/capability/text_agent.hh
  src/core/playstack_manager.hh
  src/core/routine_manager.hh
  src/core/speech_recognizer.hh
  src/core/wakeup_detector.hh
  tests/clientkit/test_clientkit_capability.cc
  tests/clientkit/test_clientkit_dialog_ux_state_aggregator.cc
  tests/clientkit/test_clientkit_nugu_runner.cc
  tests/clientkit/test_clientkit_speech_recognizer_aggregator.cc
  tests/core/test_core_focus_manager.cc
  tests/core/test_core_interaction_control_manager.cc
  tests/core/test_core_media_player.cc
  tests/core/test_core_nugu_timer.cc
  tests/core/test_core_playstack_manager.cc
  tests/core/test_core_playsync_manager.cc
  tests/core/test_core_routine_manager.cc
  tests/core/test_core_session_manager.cc
Labels: code quality

#870 build: fix default built-in option
  CMakeLists.txt
  externals/CMakeLists.txt
  src/CMakeLists.txt
Labels: ci/cd/build

#869 build: add MacOS support
  CMakeLists.txt
  externals/CMakeLists.txt
  plugins/CMakeLists.txt
  plugins/gstreamer_pcm.c
  src/base/network/http2/http2_network.c
  src/base/nugu_log.c
  src/base/nugu_plugin.c
  src/capability/audio_player_agent.hh
  src/core/audio_input_processor.cc
  tests/test_nugu_plugin.c
Labels: ci/cd/build

#871 build: add github action for macos
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
Labels: ci/cd/build

#872 build: add option for library, plugins, examples
  CMakeLists.txt
  nugu.pc.in
Labels: ci/cd/build

#873 AudioPlayer: fix parsing UpdateMetadata directive
  src/capability/audio_player_agent.cc
Labels: bug

#874 build: add ASSET_DIR option
  CMakeLists.txt
Labels: ci/cd/build

#875 plugins: add audioresample to gstreamer plugin
  plugins/gstreamer_recorder.c
Labels: enhancement

#876 build: add nugu-epd dependency to plugin
  CMakeLists.txt
  plugins/CMakeLists.txt
  src/CMakeLists.txt
Labels: ci/cd/build
