Repository nugu-developers/nugu-linux, pull requests merged in 2022-02, with the labels that each got.

#777 Thread-safety: NuguRunner
  include/clientkit/nugu_runner.hh
  src/clientkit/nugu_runner.cc
  tests/clientkit/CMakeLists.txt
  tests/clientkit/test_clientkit_nugu_runner.cc
Labels: enhancement

#780 clientkit: improve NuguRunner's performance
  include/clientkit/nugu_runner.hh
  src/clientkit/nugu_runner.cc
Labels: enhancement

#778 base: add HTTP request API
  include/base/nugu_http.h
  src/base/CMakeLists.txt
  src/base/network/http2/http2_request.c
  src/base/nugu_curl_log.c
  src/base/nugu_curl_log.h
  src/base/nugu_http.c
  tests/CMakeLists.txt
  tests/test_nugu_http.c
  tests/test_server.js
Labels: enhancement

#782 clientkit: add Authentication API
  include/clientkit/nugu_auth.hh
  src/clientkit/nugu_auth.cc
  tests/clientkit/CMakeLists.txt
  tests/clientkit/test_clientkit_auth.cc
Labels: enhancement

#783 clientkit: add uri information getter to auth
  include/clientkit/nugu_auth.hh
  src/clientkit/nugu_auth.cc
  tests/clientkit/test_clientkit_auth.cc
Labels: enhancement

#784 clientkit: modify nugu runner policy
  include/clientkit/nugu_runner.hh
  src/clientkit/nugu_runner.cc
  tests/clientkit/test_clientkit_nugu_runner.cc
Labels: enhancement

#786 InteractionControl:Update handling InteractionControl
  src/capability/message_agent.cc
  src/capability/message_agent.hh
  src/capability/phone_call_agent.cc
  src/capability/phone_call_agent.hh
  src/capability/text_agent.cc
  src/capability/text_agent.hh
Labels: spec update

#787 CapabilityFactory:clean code about template instantiation
  src/capability/capability_factory.cc
Labels: code quality
