Repository nugu-developers/nugu-linux, pull requests merged in 2023-11, with the labels that each got.

#912 fix issues detected by clang-tidy
  examples/capability_injection/main_capability_injection.cc
  examples/profiling/main_prof.cc
  examples/response_filter/main.cc
  examples/simple_asr/main_asr.cc
  examples/simple_text/main_text.cc
  examples/simple_tts/main_tts.cc
  examples/standalone/nugu_sample_manager.cc
  examples/standalone/nugu_sdk_manager.cc
  plugins/filereader.c
  plugins/gstreamer_recorder.c
  plugins/portaudio.c
  plugins/portaudio_recorder.c
  src/base/network/http2/directives_parser.cc
  src/base/nugu_http.c
  src/base/nugu_log.c
  src/base/nugu_network_manager.c
  src/base/nugu_plugin.c
  src/base/nugu_prof.c
  src/capability/system_agent.cc
  tests/test_nugu_uuid.c
Labels: code quality

#913 core: fix record data notification
  src/core/speech_recognizer.cc
Labels: bug

#914 action: fix script to use reuse workflows
  .github/workflows/pull_request.yaml
Labels: ci/cd/build
