Repository nugu-developers/nugu-linux, pull requests merged in 2024-05, with the labels that each got.

#934 sdk: voice streaming
  CMakeLists.txt
  examples/standalone/nugu_sdk_manager.cc
  include/capability/asr_interface.hh
  include/clientkit/speech_recognizer_aggregator_interface.hh
  include/clientkit/speech_recognizer_interface.hh
  src/capability/asr_agent.cc
  src/capability/asr_agent.hh
  src/clientkit/speech_recognizer_aggregator.cc
  src/clientkit/speech_recognizer_aggregator.hh
  src/core/speech_recognizer.cc
  src/core/speech_recognizer.hh
  tests/clientkit/test_clientkit_speech_recognizer_aggregator.cc
Labels: enhancement

#936 plugin: add size check logic to speex
  plugins/speex.c
Labels: code quality

#937 core: fix AudioRecorderManager to use runner
  src/core/audio_recorder_manager.cc
  src/core/audio_recorder_manager.hh
Labels: enhancement

#938 base: change openssl based SHA1 to g_checksum
  CMakeLists.txt
  src/base/nugu_uuid.c
Labels: code quality

#939 plugins: add missing 'static' to function
  plugins/opus_encoder.c
  plugins/speex.c
Labels: code quality

#933 sdk: support window
  CMakeLists.txt
  examples/capability_injection/CMakeLists.txt
  examples/profiling/CMakeLists.txt
  examples/response_filter/CMakeLists.txt
  examples/simple_asr/CMakeLists.txt
  examples/simple_play/CMakeLists.txt
  examples/simple_text/CMakeLists.txt
  examples/simple_tts/CMakeLists.txt
  examples/standalone/CMakeLists.txt
  externals/CMakeLists.txt
  include/base/nugu_winsock.h
  nugu-no-epd.pc.in
  plugins/CMakeLists.txt
  plugins/gstreamer.c
  plugins/gstreamer_pcm.c
  plugins/gstreamer_recorder.c
  plugins/opus_encoder.c
  src/CMakeLists.txt
  src/base/network/http2/http2_network.c
  src/base/nugu_equeue.c
  src/base/nugu_log.c
  src/base/nugu_winsock.c
  src/clientkit/nugu_client_impl.cc
  src/core/audio_input_processor.cc
  tests/clientkit/test_clientkit_nugu_runner.cc
Labels: enhancement

#940 base: apply NUGU_API macro to support win32
  include/base/nugu_audio.h
  include/base/nugu_buffer.h
  include/base/nugu_decoder.h
  include/base/nugu_directive.h
  include/base/nugu_encoder.h
  include/base/nugu_equeue.h
  include/base/nugu_event.h
  include/base/nugu_http.h
  include/base/nugu_log.h
  include/base/nugu_network_manager.h
  include/base/nugu_pcm.h
  include/base/nugu_player.h
  include/base/nugu_plugin.h
  include/base/nugu_prof.h
  include/base/nugu_recorder.h
  include/base/nugu_ringbuffer.h
  include/base/nugu_timer.h
  include/base/nugu_uuid.h
  include/base/nugu_winsock.h
  nugu.h.in
  src/base/CMakeLists.txt
  src/base/nugu_audio.c
  src/base/nugu_buffer.c
  src/base/nugu_decoder.c
  src/base/nugu_directive.c
  src/base/nugu_encoder.c
  src/base/nugu_equeue.c
  src/base/nugu_event.c
  src/base/nugu_http.c
  src/base/nugu_log.c
  src/base/nugu_network_manager.c
  src/base/nugu_pcm.c
  src/base/nugu_player.c
  src/base/nugu_plugin.c
  src/base/nugu_prof.c
  src/base/nugu_recorder.c
  src/base/nugu_ringbuffer.c
  src/base/nugu_timer.c
  src/base/nugu_uuid.c
  tests/clientkit/CMakeLists.txt
  tests/core/CMakeLists.txt
Labels: enhancement

#941 fix time and random API to portable
  examples/profiling/main_prof.cc
  include/base/nugu_prof.h
  include/base/nugu_uuid.h
  plugins/filedump.c
  plugins/filereader.c
  plugins/gstreamer_pcm.c
  plugins/gstreamer_recorder.c
  plugins/opus.c
  plugins/opus_encoder.c
  plugins/portaudio_pcm_async.c
  plugins/portaudio_pcm_sync.c
  plugins/portaudio_recorder.c
  plugins/speex.c
  src/base/network/http2/threadsync.c
  src/base/network/http2/v1_ping.c
  src/base/nugu_log.c
  src/base/nugu_network_manager.c
  src/base/nugu_prof.c
  src/base/nugu_recorder.c
  src/base/nugu_uuid.c
  src/capability/display_agent.cc
  src/capability/display_render_helper.cc
  tests/test_nugu_uuid.c
Labels: enhancement

#943 build: add PDB info to CMake objects
  plugins/CMakeLists.txt
  src/base/CMakeLists.txt
  src/capability/CMakeLists.txt
  src/clientkit/CMakeLists.txt
  src/core/CMakeLists.txt
Labels: enhancement

#944 base: fix nugu_plugin module to support WIN32
  src/base/nugu_plugin.c
  tests/CMakeLists.txt
  tests/plugin_nugu_custom.c
  tests/test_nugu_plugin.c
Labels: enhancement

#945 base: disable syslog in WIN32 platform
  src/base/nugu_log.c
Labels: ci/cd/build

#946 add WIN32 ifdef guard to winsock
  CMakeLists.txt
  src/base/network/http2/http2_network.c
  src/base/nugu_equeue.c
  src/base/nugu_winsock.c
  src/clientkit/nugu_client_impl.cc
Labels: ci/cd/build

#947 capability: add TTSAgent build error on WIN32
  src/capability/tts_agent.hh
Labels: code quality

#949 build: fix link option
  CMakeLists.txt
  examples/capability_injection/CMakeLists.txt
  examples/profiling/CMakeLists.txt
  examples/response_filter/CMakeLists.txt
  examples/simple_asr/CMakeLists.txt
  examples/simple_play/CMakeLists.txt
  examples/simple_text/CMakeLists.txt
  examples/simple_tts/CMakeLists.txt
  examples/standalone/CMakeLists.txt
  plugins/CMakeLists.txt
  src/CMakeLists.txt
  tests/CMakeLists.txt
  tests/clientkit/CMakeLists.txt
  tests/core/CMakeLists.txt
Labels: ci/cd/build

#950 add _WIN32 to existing __MSYS__ guard
  plugins/gstreamer.c
  plugins/gstreamer_pcm.c
  plugins/gstreamer_recorder.c
  src/core/audio_input_processor.cc
  tests/clientkit/test_clientkit_nugu_runner.cc
Labels: ci/cd/build

#951 core: remove casting in the TTSPlayer
  src/core/tts_player.cc
Labels: code quality

#952 plugins: disable link for dump file on WIN32
  plugins/filedump.c
  plugins/filereader.c
  plugins/gstreamer_pcm.c
  plugins/gstreamer_recorder.c
  plugins/opus.c
  plugins/portaudio_pcm_async.c
  plugins/portaudio_pcm_sync.c
  plugins/portaudio_recorder.c
Labels: ci/cd/build

#953 refactoring build scripts
  CMakeLists.txt
  examples/CMakeLists.txt
  externals/CMakeLists.txt
  include/buildin.h
  nugu-no-epd.pc.in
  nugu.pc.in
  plugins/CMakeLists.txt
  src/CMakeLists.txt
  src/capability/CMakeLists.txt
  src/clientkit/CMakeLists.txt
  src/core/CMakeLists.txt
Labels: ci/cd/build

#955 base: fix ANSI escape code for log message
  include/base/nugu_log.h
  src/base/nugu_log.c
Labels: enhancement

#956 plugin: add 'nugu_plugin_' prefix to filename
  plugins/CMakeLists.txt
  src/base/nugu_plugin.c
Labels: enhancement

#957 build: fix gstreamer build options
  CMakeLists.txt
  plugins/CMakeLists.txt
  src/CMakeLists.txt
Labels: ci/cd/build

#958 build: fix BUILTIN_PLUGIN feature
  CMakeLists.txt
Labels: ci/cd/build

#954 clientkit: apply NUGU_API macro to support win32
  include/capability/asr_interface.hh
  include/capability/audio_player_interface.hh
  include/capability/battery_interface.hh
  include/capability/bluetooth_interface.hh
  include/capability/capability_factory.hh
  include/capability/chips_interface.hh
  include/capability/display_interface.hh
  include/capability/extension_interface.hh
  include/capability/location_interface.hh
  include/capability/message_interface.hh
  include/capability/mic_interface.hh
  include/capability/nudge_interface.hh
  include/capability/phone_call_interface.hh
  include/capability/routine_interface.hh
  include/capability/session_interface.hh
  include/capability/sound_interface.hh
  include/capability/speaker_interface.hh
  include/capability/system_interface.hh
  include/capability/text_interface.hh
  include/capability/tts_interface.hh
  include/capability/utility_interface.hh
  include/clientkit/capability.hh
  include/clientkit/capability_helper_interface.hh
  include/clientkit/capability_interface.hh
  include/clientkit/dialog_ux_state_aggregator_interface.hh
  include/clientkit/directive_sequencer_interface.hh
  include/clientkit/focus_manager_interface.hh
  include/clientkit/interaction_control_manager_interface.hh
  include/clientkit/media_player_interface.hh
  include/clientkit/network_manager_interface.hh
  include/clientkit/nugu_auth.hh
  include/clientkit/nugu_client.hh
  include/clientkit/nugu_core_container_interface.hh
  include/clientkit/nugu_http_rest.hh
  include/clientkit/nugu_runner.hh
  include/clientkit/nugu_timer_interface.hh
  include/clientkit/playsync_manager_interface.hh
  include/clientkit/routine_manager_interface.hh
  include/clientkit/session_manager_interface.hh
  include/clientkit/speech_recognizer_aggregator_interface.hh
  include/clientkit/speech_recognizer_interface.hh
  include/clientkit/wakeup_interface.hh
  src/capability/CMakeLists.txt
  src/capability/capability_factory.cc
  src/clientkit/CMakeLists.txt
Labels: enhancement

#959 base: initialize mutex
  src/base/nugu_equeue.c
  src/base/nugu_prof.c
Labels: bug

#960 tests: fix plugin testcase
  tests/CMakeLists.txt
  tests/test_nugu_plugin.c
Labels: ci/cd/build

#961 build: add missing NUGU_LIBRARY_BUILD define
  plugins/CMakeLists.txt
  src/base/CMakeLists.txt
  src/clientkit/CMakeLists.txt
  src/core/CMakeLists.txt
Labels: ci/cd/build

#962 tests: support msvc
  src/clientkit/dialog_ux_state_aggregator.hh
  src/clientkit/speech_recognizer_aggregator.hh
  src/core/directive_sequencer.hh
  src/core/focus_manager.hh
  src/core/interaction_control_manager.hh
  src/core/media_player.hh
  src/core/nugu_timer.hh
  src/core/playstack_manager.hh
  src/core/playsync_manager.hh
  src/core/routine_manager.hh
  src/core/session_manager.hh
  tests/core/CMakeLists.txt
  tests/core/test_core_focus_manager.cc
Labels: enhancement
