Repository nugu-developers/nugu-linux, pull requests merged in 2024-04, with the labels that each got.

#922 build: fix macOS build error
  CMakeLists.txt
  src/base/CMakeLists.txt
Labels: ci/cd/build

#923 action: fix CodeQL action to use manual build
  .github/workflows/codeql-analysis.yaml
Labels: ci/cd/build

#924 fix the method documentation
  include/capability/audio_player_interface.hh
  include/clientkit/capability.hh
  include/clientkit/capability_interface.hh
  include/clientkit/network_manager_interface.hh
  include/clientkit/nugu_core_container_interface.hh
  include/clientkit/nugu_timer_interface.hh
  include/clientkit/playsync_manager_interface.hh
  src/core/nugu_core_container.cc
  src/core/nugu_core_container.hh
  src/core/nugu_timer.cc
  src/core/nugu_timer.hh
Labels: documentation

#925 sdk: memory deallocation
  examples/response_filter/filter.cc
  plugins/filedump.c
  plugins/filereader.c
  plugins/gstreamer_pcm.c
  plugins/gstreamer_recorder.c
  plugins/opus.c
  plugins/opus_encoder.c
  plugins/portaudio_pcm_async.c
  plugins/portaudio_pcm_sync.c
  plugins/portaudio_recorder.c
  plugins/speex.c
  src/base/network/dg_server.c
  src/base/network/http2/directives_parser.cc
  src/base/network/http2/http2_network.c
  src/base/network/http2/http2_request.c
  src/base/network/http2/v1_event.c
  src/base/network/http2/v1_event_attachment.c
  src/base/network/http2/v2_events.c
  src/base/nugu_directive.c
  src/base/nugu_equeue.c
  src/base/nugu_event.c
  src/base/nugu_http.c
  src/base/nugu_network_manager.c
  src/base/nugu_pcm.c
  src/base/nugu_prof.c
  src/base/nugu_recorder.c
  src/core/audio_input_processor.cc
  src/core/media_player.cc
  tests/clientkit/test_clientkit_nugu_runner.cc
  tests/core/test_core_playsync_manager.cc
  tests/test_nugu_event.c
  tests/test_nugu_recorder.c
Labels: code quality

#926 clikentkit: fix hangup
  src/clientkit/nugu_client_impl.cc
Labels: bug

#928 build: exclude portaudio plugin from default list
  CMakeLists.txt
Labels: ci/cd/build

#929 build: fix component name
  CMakeLists.txt
  examples/standalone/CMakeLists.txt
  plugins/CMakeLists.txt
  src/CMakeLists.txt
Labels: ci/cd/build

#930 plugin: fix plugin name
  plugins/CMakeLists.txt
  plugins/filedump.c
  plugins/filereader.c
  plugins/gstreamer.c
  plugins/gstreamer_pcm.c
  plugins/gstreamer_recorder.c
  plugins/opus.c
  plugins/opus_encoder.c
  plugins/portaudio.c
  plugins/portaudio_pcm_async.c
  plugins/portaudio_pcm_sync.c
  plugins/portaudio_recorder.c
  plugins/speex.c
Labels: code quality

#927 fix plugin architecture
  .gitignore
  CMakeLists.txt
  include/base/nugu_plugin.h
  include/buildin.h
  plugins/CMakeLists.txt
  plugins/dummy.c
  plugins/filedump.c
  plugins/filereader.c
  plugins/gstreamer.c
  plugins/gstreamer_pcm.c
  plugins/gstreamer_recorder.c
  plugins/opus.c
  plugins/opus_encoder.c
  plugins/portaudio.c
  plugins/portaudio_pcm_async.c
  plugins/portaudio_pcm_sync.c
  plugins/portaudio_recorder.c
  plugins/speex.c
  src/CMakeLists.txt
  src/base/builtin.h.in
  src/base/nugu_plugin.c
  src/clientkit/nugu_client_impl.cc
  tests/plugin_nugu.c
  tests/plugin_nugu_custom.c
Labels: enhancement, ci/cd/build

#931 build: fix build error on homebrew
  CMakeLists.txt
Labels: ci/cd/build

#932 sdk: memory deallocation
  src/capability/tts_agent.cc
Labels: bug
