Repository nugu-developers/nugu-linux, pull requests merged in 2024-06, with the labels that each got.

#964 core: fix SpeechRecognizer to support WIN32
  src/core/speech_recognizer.cc
Labels: enhancement

#966 build: fix built-in opus library build error
  CMakeLists.txt
Labels: ci/cd/build

#968 base: fix curl log to skip CRLF data
  src/base/nugu_curl_log.c
Labels: code quality

#970 build: fix plugin build error on macos ffi
  CMakeLists.txt
  plugins/CMakeLists.txt
Labels: bug, ci/cd/build

#974 improve AudioPlayer playsync handling
  src/capability/audio_player_agent.cc
Labels: enhancement

#973 fix bug: seek time unit
  src/capability/audio_player_agent.cc
Labels: bug

#971 fix media player position handling
  src/core/media_player.cc
  src/core/media_player.hh
Labels: bug

#976 build: fix CMakeLists.txt to check builtin options
  CMakeLists.txt
Labels: ci/cd/build

#977 capability: fix bug
  src/capability/audio_player_agent.cc
Labels: bug

#978 core: update position
  src/core/media_player.cc
Labels: bug
